"""initial_schema

Revision ID: t1a2b3c4d5e6
Revises: 
Create Date: 2026-09-28 02:25:29

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 't1a2b3c4d5e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_timestamp'), 'activity_log', ['timestamp'], unique=False)
    op.create_table('agent_session_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('compacted', sa.Integer(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('carrier_marker', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asm_sess_active', 'agent_session_messages', ['session_id', 'active'], unique=False)
    op.create_index('idx_asm_sess_created', 'agent_session_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_session_messages_active'), 'agent_session_messages', ['active'], unique=False)
    op.create_index(op.f('ix_agent_session_messages_compacted'), 'agent_session_messages', ['compacted'], unique=False)
    op.create_index(op.f('ix_agent_session_messages_created_at'), 'agent_session_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_session_messages_session_id'), 'agent_session_messages', ['session_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parent_session_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('system_prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_sess_user_plat', 'agent_sessions', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_agent_sessions_parent_session_id'), 'agent_sessions', ['parent_session_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('step_hours', sa.Integer(), nullable=False),
    sa.Column('initial_equity', sa.Float(), nullable=False),
    sa.Column('final_equity', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('settings_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bond_yield_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_tenor', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yield_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_tenor', 'date', name='uq_bond_yield_country_date')
    )
    op.create_index('idx_bond_yield_ct_date', 'bond_yield_data', ['country_tenor', 'date'], unique=False)
    op.create_table('candidate_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('lesson_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluated_trades_count', sa.Integer(), nullable=False),
    sa.Column('win_rate_delta', sa.Float(), nullable=False),
    sa.Column('sharpe_delta', sa.Float(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('condition_tags', sa.String(length=255), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_lessons_status'), 'candidate_lessons', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_lessons_symbol'), 'candidate_lessons', ['symbol'], unique=False)
    op.create_table('central_bank_rate_expectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=20), nullable=False),
    sa.Column('meeting_date', sa.String(length=30), nullable=False),
    sa.Column('current_rate', sa.Float(), nullable=False),
    sa.Column('prob_hike', sa.Float(), nullable=False),
    sa.Column('prob_hold', sa.Float(), nullable=False),
    sa.Column('prob_cut', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cb_rate_exp_bank_date', 'central_bank_rate_expectations', ['bank', 'meeting_date'], unique=False)
    op.create_index(op.f('ix_central_bank_rate_expectations_bank'), 'central_bank_rate_expectations', ['bank'], unique=False)
    op.create_table('context_spill_blobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_id', sa.String(length=64), nullable=False),
    sa.Column('cycle_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('payload_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spill_cycle_tool', 'context_spill_blobs', ['cycle_id', 'tool_name'], unique=False)
    op.create_index(op.f('ix_context_spill_blobs_blob_id'), 'context_spill_blobs', ['blob_id'], unique=True)
    op.create_index(op.f('ix_context_spill_blobs_created_at'), 'context_spill_blobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_context_spill_blobs_cycle_id'), 'context_spill_blobs', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_context_spill_blobs_tool_name'), 'context_spill_blobs', ['tool_name'], unique=False)
    op.create_table('cot_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_code', sa.String(length=20), nullable=False),
    sa.Column('dealer_long', sa.Integer(), nullable=False),
    sa.Column('dealer_short', sa.Integer(), nullable=False),
    sa.Column('asset_mgr_long', sa.Integer(), nullable=False),
    sa.Column('asset_mgr_short', sa.Integer(), nullable=False),
    sa.Column('leveraged_long', sa.Integer(), nullable=False),
    sa.Column('leveraged_short', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cot_market_date', 'cot_report', ['market_code', 'report_date'], unique=False)
    op.create_index(op.f('ix_cot_report_market_code'), 'cot_report', ['market_code'], unique=False)
    op.create_table('cycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'sequence', name='uq_cycle_event_seq')
    )
    op.create_index('idx_cycle_event_type', 'cycle_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_cycle_events_cycle_id'), 'cycle_events', ['cycle_id'], unique=False)
    op.create_table('cycle_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('news_scraped', sa.Integer(), nullable=False),
    sa.Column('calendar_scraped', sa.Integer(), nullable=False),
    sa.Column('stage1_success', sa.Boolean(), nullable=False),
    sa.Column('stage1_tokens_in', sa.Integer(), nullable=False),
    sa.Column('stage1_tokens_out', sa.Integer(), nullable=False),
    sa.Column('assets_analyzed', sa.Integer(), nullable=False),
    sa.Column('assets_skipped', sa.Integer(), nullable=False),
    sa.Column('decisions_buy', sa.Integer(), nullable=False),
    sa.Column('decisions_sell', sa.Integer(), nullable=False),
    sa.Column('decisions_wait', sa.Integer(), nullable=False),
    sa.Column('decisions_avoid', sa.Integer(), nullable=False),
    sa.Column('stage2_tokens_in', sa.Integer(), nullable=False),
    sa.Column('stage2_tokens_out', sa.Integer(), nullable=False),
    sa.Column('trades_proposed', sa.Integer(), nullable=False),
    sa.Column('trades_executed', sa.Integer(), nullable=False),
    sa.Column('trades_blocked', sa.Integer(), nullable=False),
    sa.Column('api_cost_usd', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('data_completeness_score', sa.Float(), nullable=True),
    sa.Column('tool_success_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_performance_cycle_at'), 'cycle_performance', ['cycle_at'], unique=False)
    op.create_table('decision_memory_backtest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale_summary', sa.Text(), nullable=True),
    sa.Column('raw_return', sa.Float(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('outcome_status', sa.String(length=20), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_memory_backtest_run_id'), 'decision_memory_backtest', ['run_id'], unique=False)
    op.create_table('dxy_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('economic_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('actual', sa.String(length=50), nullable=True),
    sa.Column('forecast', sa.String(length=50), nullable=True),
    sa.Column('previous', sa.String(length=50), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('surprise_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'event_name', 'event_time', name='uq_calendar_event')
    )
    op.create_index(op.f('ix_economic_calendar_currency'), 'economic_calendar', ['currency'], unique=False)
    op.create_index(op.f('ix_economic_calendar_event_time'), 'economic_calendar', ['event_time'], unique=False)
    op.create_table('fedwatch_probabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.String(length=20), nullable=False),
    sa.Column('probabilities_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fundamental_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('structured_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_sentiment', sa.String(length=50), nullable=True),
    sa.Column('debate_bull_thesis', sa.Text(), nullable=True),
    sa.Column('debate_bear_thesis', sa.Text(), nullable=True),
    sa.Column('debate_winner', sa.String(length=20), nullable=True),
    sa.Column('debate_escalation_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fvg_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('gap_high', sa.Float(), nullable=False),
    sa.Column('gap_low', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fvg_sym_tf', 'fvg_zones', ['symbol', 'timeframe'], unique=False)
    op.create_table('interest_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=20), nullable=False),
    sa.Column('rate_percent', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_meeting_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidity_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('zone_high', sa.Float(), nullable=False),
    sa.Column('zone_low', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('identified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_liq_sym_tf', 'liquidity_zones', ['symbol', 'timeframe'], unique=False)
    op.create_table('market_chronicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('currencies_affected', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('source_news_id', sa.Integer(), nullable=True),
    sa.Column('source_brief_id', sa.Integer(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chronicle_fts', 'market_chronicle', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_market_chronicle_event_date'), 'market_chronicle', ['event_date'], unique=False)
    op.create_table('news_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_hours', sa.Integer(), nullable=False),
    sa.Column('digest_text', sa.Text(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_digest_slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('period_hours', sa.Float(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('breaking_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('currency_sections', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_digest_slices_period', 'news_digest_slices', ['period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_news_digest_slices_period_start'), 'news_digest_slices', ['period_start'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency_tags', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('sentiment', sa.String(length=255), nullable=True),
    sa.Column('prefilter_flags', sa.String(length=50), nullable=True),
    sa.Column('key_data_point', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_source_fetched', 'news_items', ['source', 'fetched_at'], unique=False)
    op.create_index('idx_news_url', 'news_items', ['url'], unique=False)
    op.create_index(op.f('ix_news_items_source'), 'news_items', ['source'], unique=False)
    op.create_table('order_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('price_high', sa.Float(), nullable=False),
    sa.Column('price_low', sa.Float(), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mitigated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ob_sym_tf', 'order_blocks', ['symbol', 'timeframe'], unique=False)
    op.create_table('orders_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_screening_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('screened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_bias', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('consensus_bullish_pct', sa.Float(), nullable=False),
    sa.Column('consensus_bearish_pct', sa.Float(), nullable=False),
    sa.Column('has_timeframe_conflict', sa.Boolean(), nullable=False),
    sa.Column('significant_timeframes_json', sa.Text(), nullable=True),
    sa.Column('per_timeframe_json', sa.Text(), nullable=True),
    sa.Column('full_result_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pattern_cache_sym_at', 'pattern_screening_cache', ['symbol', 'screened_at'], unique=False)
    op.create_index(op.f('ix_pattern_screening_cache_screened_at'), 'pattern_screening_cache', ['screened_at'], unique=False)
    op.create_index(op.f('ix_pattern_screening_cache_symbol'), 'pattern_screening_cache', ['symbol'], unique=False)
    op.create_table('playbook_rule_attributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_hash', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('times_triggered', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('losses_count', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecation_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playbook_rule_sym_stat', 'playbook_rule_attributions', ['symbol', 'status'], unique=False)
    op.create_index(op.f('ix_playbook_rule_attributions_rule_hash'), 'playbook_rule_attributions', ['rule_hash'], unique=False)
    op.create_index(op.f('ix_playbook_rule_attributions_status'), 'playbook_rule_attributions', ['status'], unique=False)
    op.create_index(op.f('ix_playbook_rule_attributions_symbol'), 'playbook_rule_attributions', ['symbol'], unique=False)
    op.create_table('prescreen_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('price_at_check', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_4h_after', sa.Float(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prescreen_symbol_time', 'prescreen_log', ['symbol', 'checked_at'], unique=False)
    op.create_index(op.f('ix_prescreen_log_symbol'), 'prescreen_log', ['symbol'], unique=False)
    op.create_table('price_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_price_sym_tf_ts')
    )
    op.create_index('idx_price_sym_tf_ts', 'price_ohlcv', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_table('risk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('current_drawdown', sa.Float(), nullable=False),
    sa.Column('trading_paused', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('unpause_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_state_date'), 'risk_state', ['date'], unique=False)
    op.create_table('sr_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('price_high', sa.Float(), nullable=False),
    sa.Column('price_low', sa.Float(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('last_touched', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sr_sym_tf', 'sr_zones', ['symbol', 'timeframe'], unique=False)
    op.create_table('structure_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sb_sym_tf', 'structure_breaks', ['symbol', 'timeframe'], unique=False)
    op.create_table('swing_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_swing_sym_tf', 'swing_points', ['symbol', 'timeframe'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_prompts',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicator_sym_tf_ts', 'technical_indicators', ['symbol', 'timeframe', 'timestamp', 'indicator_name'], unique=False)
    op.create_table('telegram_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tg_user_timestamp', 'telegram_conversations', ['telegram_user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telegram_conversations_telegram_user_id'), 'telegram_conversations', ['telegram_user_id'], unique=False)
    op.create_table('telegram_topic_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'topic_id', name='uq_telegram_topic_chat_topic')
    )
    op.create_index('idx_tg_topic_chat_topic', 'telegram_topic_bindings', ['chat_id', 'topic_id'], unique=False)
    op.create_index(op.f('ix_telegram_topic_bindings_chat_id'), 'telegram_topic_bindings', ['chat_id'], unique=False)
    op.create_index(op.f('ix_telegram_topic_bindings_session_id'), 'telegram_topic_bindings', ['session_id'], unique=True)
    op.create_index(op.f('ix_telegram_topic_bindings_topic_id'), 'telegram_topic_bindings', ['topic_id'], unique=False)
    op.create_table('timesfm_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_steps', sa.Integer(), nullable=False),
    sa.Column('quantiles_json', sa.Text(), nullable=False),
    sa.Column('expected_range', sa.Float(), nullable=False),
    sa.Column('quantile_skew', sa.Float(), nullable=False),
    sa.Column('volatility_expansion_ratio', sa.Float(), nullable=False),
    sa.Column('reachability_envelope', sa.Text(), nullable=True),
    sa.Column('model_backend', sa.String(length=50), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_timesfm_sym_time', 'timesfm_forecasts', ['symbol', 'timeframe', 'generated_at'], unique=False)
    op.create_index(op.f('ix_timesfm_forecasts_generated_at'), 'timesfm_forecasts', ['generated_at'], unique=False)
    op.create_index(op.f('ix_timesfm_forecasts_symbol'), 'timesfm_forecasts', ['symbol'], unique=False)
    op.create_table('token_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('task_role', sa.String(length=100), nullable=True),
    sa.Column('subsystem', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('cycle_id', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('thinking_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('slot_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_log_cycle_id'), 'token_usage_log', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_token_usage_log_status'), 'token_usage_log', ['status'], unique=False)
    op.create_index(op.f('ix_token_usage_log_subsystem'), 'token_usage_log', ['subsystem'], unique=False)
    op.create_index(op.f('ix_token_usage_log_symbol'), 'token_usage_log', ['symbol'], unique=False)
    op.create_index(op.f('ix_token_usage_log_task_role'), 'token_usage_log', ['task_role'], unique=False)
    op.create_index(op.f('ix_token_usage_log_thinking_tokens'), 'token_usage_log', ['thinking_tokens'], unique=False)
    op.create_index(op.f('ix_token_usage_log_timestamp'), 'token_usage_log', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('trading_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('ts_created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_events_correlation_id'), 'trading_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_trading_events_event_type'), 'trading_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_trading_events_seq'), 'trading_events', ['seq'], unique=False)
    op.create_index(op.f('ix_trading_events_ts_created'), 'trading_events', ['ts_created'], unique=False)
    op.create_table('trading_state_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('state_payload', sa.JSON(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tslog_cycle', 'trading_state_logs', ['cycle_id'], unique=False)
    op.create_index('idx_tslog_fts', 'trading_state_logs', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_trading_state_logs_cycle_id'), 'trading_state_logs', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_trading_state_logs_recorded_at'), 'trading_state_logs', ['recorded_at'], unique=False)
    op.create_table('treasury_yields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenor', sa.String(length=32), nullable=False),
    sa.Column('yield_percent', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_treasury_tenor_date', 'treasury_yields', ['tenor', 'date'], unique=False)
    op.create_table('user_market_intel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=50), nullable=False),
    sa.Column('intel_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('affected_symbols', sa.String(length=100), nullable=False),
    sa.Column('directive', sa.String(length=30), nullable=False),
    sa.Column('target_cycle', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_cycle_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_market_intel_active_exp', 'user_market_intel', ['is_active', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_market_intel_expires_at'), 'user_market_intel', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_market_intel_is_active'), 'user_market_intel', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_market_intel_telegram_user_id'), 'user_market_intel', ['telegram_user_id'], unique=False)
    op.create_table('vix_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('asset_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_zone', sa.Text(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('reevaluation_trigger', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('priced_in_score', sa.Integer(), nullable=True),
    sa.Column('priced_in_override_justification', sa.Text(), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('confluence_factors_json', sa.Text(), nullable=True),
    sa.Column('specialist_biases_json', sa.Text(), nullable=True),
    sa.Column('invalidation_price', sa.Float(), nullable=True),
    sa.Column('invalidation_direction', sa.String(length=10), nullable=True),
    sa.Column('execution_status', sa.String(length=20), nullable=True),
    sa.Column('execution_notes', sa.Text(), nullable=True),
    sa.Column('market_regime_at_analysis', sa.String(length=50), nullable=True),
    sa.Column('risk_multiplier', sa.Float(), nullable=True),
    sa.Column('debate_bull_thesis', sa.Text(), nullable=True),
    sa.Column('debate_bear_dissent', sa.Text(), nullable=True),
    sa.Column('debate_verdict', sa.String(length=50), nullable=True),
    sa.Column('debate_reason', sa.Text(), nullable=True),
    sa.Column('arbitration_reason', sa.Text(), nullable=True),
    sa.Column('decision_source', sa.String(length=50), nullable=True),
    sa.Column('source_strategy_id', sa.String(length=50), nullable=True),
    sa.Column('pair_group_id', sa.String(length=50), nullable=True),
    sa.Column('was_debate_modified', sa.Boolean(), nullable=True),
    sa.Column('was_ssvp_suppressed', sa.Boolean(), nullable=True),
    sa.Column('context_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('brief_age_at_analysis_hours', sa.Float(), nullable=True),
    sa.Column('ssvp_cds_score_at_analysis', sa.Float(), nullable=True),
    sa.Column('adr_at_analysis', sa.Float(), nullable=True),
    sa.Column('adr_tp_pct_used', sa.Float(), nullable=True),
    sa.Column('adr_sl_pct_used', sa.Float(), nullable=True),
    sa.Column('price_at_analysis', sa.Float(), nullable=True),
    sa.Column('price_4h_after', sa.Float(), nullable=True),
    sa.Column('price_24h_after', sa.Float(), nullable=True),
    sa.Column('direction_correct_4h', sa.Boolean(), nullable=True),
    sa.Column('direction_correct_24h', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['fundamental_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_sym_date', 'asset_analysis', ['symbol', 'generated_at'], unique=False)
    op.create_index(op.f('ix_asset_analysis_pair_group_id'), 'asset_analysis', ['pair_group_id'], unique=False)
    op.create_index(op.f('ix_asset_analysis_source_strategy_id'), 'asset_analysis', ['source_strategy_id'], unique=False)
    op.create_index(op.f('ix_asset_analysis_symbol'), 'asset_analysis', ['symbol'], unique=False)
    op.create_table('backtest_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('pnl_pips', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('executed_lots', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_classification_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('symbol_checked', sa.String(length=20), nullable=False),
    sa.Column('classified_impact', sa.String(length=20), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_at_classification', sa.Float(), nullable=True),
    sa.Column('price_2h_after', sa.Float(), nullable=True),
    sa.Column('move_pct_2h', sa.Float(), nullable=True),
    sa.Column('outcome_matched_classification', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ncls_outcome_pending', 'news_classification_outcomes', ['checked_at', 'classified_at'], unique=False)
    op.create_table('decision_reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('rationale_summary', sa.Text(), nullable=True),
    sa.Column('outcome_pnl_usd', sa.Float(), nullable=True),
    sa.Column('holding_hours', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('was_profitable', sa.Boolean(), nullable=True),
    sa.Column('reflection_text', sa.Text(), nullable=True),
    sa.Column('next_trade_adjustment', sa.Text(), nullable=True),
    sa.Column('specific_lesson', sa.Text(), nullable=True),
    sa.Column('lesson_tags', sa.String(length=500), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('alpha_return', sa.Float(), nullable=True),
    sa.Column('benchmark_name', sa.String(length=50), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('alpha_lesson', sa.Text(), nullable=True),
    sa.Column('process_was_sound', sa.Boolean(), nullable=True),
    sa.Column('outcome_process_classification', sa.String(length=50), nullable=True),
    sa.Column('macro_thesis_correct', sa.Boolean(), nullable=True),
    sa.Column('debate_summary', sa.Text(), nullable=True),
    sa.Column('debate_verdict', sa.String(length=20), nullable=True),
    sa.Column('pre_debate_confidence', sa.Float(), nullable=True),
    sa.Column('is_paper_whatif', sa.Boolean(), nullable=False),
    sa.Column('whatif_reason', sa.String(length=50), nullable=True),
    sa.Column('whatif_entry_price', sa.Float(), nullable=True),
    sa.Column('whatif_price_24h', sa.Float(), nullable=True),
    sa.Column('whatif_hypothetical_pnl_pips', sa.Float(), nullable=True),
    sa.Column('whatif_sl_would_hit', sa.Boolean(), nullable=True),
    sa.Column('whatif_tp_would_hit', sa.Boolean(), nullable=True),
    sa.Column('whatif_direction_correct', sa.Boolean(), nullable=True),
    sa.Column('context_cds_score', sa.Float(), nullable=True),
    sa.Column('context_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('is_context_contaminated', sa.Boolean(), nullable=False),
    sa.Column('contamination_reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drefl_created', 'decision_reflections', ['created_at'], unique=False)
    op.create_index('idx_drefl_fts', 'decision_reflections', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_drefl_paper', 'decision_reflections', ['is_paper_whatif', 'status'], unique=False)
    op.create_index('idx_drefl_symbol_status', 'decision_reflections', ['symbol', 'status'], unique=False)
    op.create_index(op.f('ix_decision_reflections_symbol'), 'decision_reflections', ['symbol'], unique=False)
    op.create_table('mt5_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_analysis_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mt5_ticket', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mt5_signals_asset_analysis_id'), 'mt5_signals', ['asset_analysis_id'], unique=False)
    op.create_index(op.f('ix_mt5_signals_symbol'), 'mt5_signals', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=False),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('slippage_pips', sa.Float(), nullable=False),
    sa.Column('requested_volume', sa.Float(), nullable=False),
    sa.Column('filled_volume', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_SUBMIT', 'INTENT_COMMITTED', 'SUBMITTED', 'ACCEPTED', 'PARTIALLY_FILLED', 'FILLED', 'REJECTED', 'EXPIRED', 'CANCELLED', 'INTERRUPTED', 'ABORT_REQUESTED', name='orderstatus', native_enum=False, length=30), nullable=False),
    sa.Column('replay_policy', sa.String(length=20), nullable=False),
    sa.Column('intent_committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mt5_ticket', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_analysis_id'), 'orders', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_mt5_ticket'), 'orders', ['mt5_ticket'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('paper_trade_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=100), nullable=True),
    sa.Column('detection_method', sa.String(length=100), nullable=True),
    sa.Column('risk_pct', sa.Float(), nullable=True),
    sa.Column('entry_condition_type', sa.String(length=20), nullable=True),
    sa.Column('stated_entry_price', sa.Float(), nullable=True),
    sa.Column('is_pending_fill', sa.Boolean(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('holding_hours', sa.Float(), nullable=True),
    sa.Column('slippage_applied', sa.Float(), nullable=True),
    sa.Column('partially_filled', sa.Boolean(), nullable=False),
    sa.Column('requested_lot', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('decision_source', sa.String(length=50), nullable=True),
    sa.Column('was_debate_modified', sa.Boolean(), nullable=True),
    sa.Column('was_ssvp_suppressed', sa.Boolean(), nullable=True),
    sa.Column('mae_pips', sa.Float(), nullable=True),
    sa.Column('mfe_pips', sa.Float(), nullable=True),
    sa.Column('sl_slippage_pips', sa.Float(), nullable=True),
    sa.Column('entry_session', sa.String(length=30), nullable=True),
    sa.Column('market_regime', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paper_trade_status', 'paper_trade_records', ['status'], unique=False)
    op.create_index('idx_paper_trade_symbol', 'paper_trade_records', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trade_records_analysis_id'), 'paper_trade_records', ['analysis_id'], unique=False)
    op.create_table('trade_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('take_profit_1', sa.Float(), nullable=True),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=False),
    sa.Column('atr_at_creation', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_plan_symbol_status', 'trade_plans', ['symbol', 'status'], unique=False)
    op.create_index(op.f('ix_trade_plans_analysis_id'), 'trade_plans', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_trade_plans_status'), 'trade_plans', ['status'], unique=False)
    op.create_index(op.f('ix_trade_plans_symbol'), 'trade_plans', ['symbol'], unique=False)
    op.create_table('trade_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_analysis_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trigger_status', 'trade_triggers', ['status'], unique=False)
    op.create_index(op.f('ix_trade_triggers_asset_analysis_id'), 'trade_triggers', ['asset_analysis_id'], unique=False)
    op.create_table('confluence_factor_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_trade_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('factor_name', sa.String(length=50), nullable=False),
    sa.Column('was_present', sa.Boolean(), nullable=False),
    sa.Column('trade_outcome', sa.String(length=20), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.ForeignKeyConstraint(['paper_trade_id'], ['paper_trade_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cfo_factor', 'confluence_factor_outcomes', ['factor_name'], unique=False)
    op.create_index('idx_cfo_outcome', 'confluence_factor_outcomes', ['trade_outcome'], unique=False)
    op.create_index('idx_cfo_symbol', 'confluence_factor_outcomes', ['symbol'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('mt5_ticket', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('initial_volume', sa.Float(), nullable=True),
    sa.Column('requested_volume', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('slippage_pips', sa.Float(), nullable=True),
    sa.Column('partially_filled', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('pair_group_id', sa.String(length=50), nullable=True),
    sa.Column('trailing_override_json', sa.Text(), nullable=True),
    sa.Column('mae_pips', sa.Float(), nullable=True),
    sa.Column('mfe_pips', sa.Float(), nullable=True),
    sa.Column('sl_slippage_pips', sa.Float(), nullable=True),
    sa.Column('entry_session', sa.String(length=30), nullable=True),
    sa.Column('market_regime', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_ticket')
    )
    op.create_index('idx_position_status', 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_analysis_id'), 'positions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_positions_order_id'), 'positions', ['order_id'], unique=False)
    op.create_index(op.f('ix_positions_pair_group_id'), 'positions', ['pair_group_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index('uq_position_analysis_open', 'positions', ['analysis_id', 'mt5_ticket'], unique=True, postgresql_where=sa.text("status = 'open' AND analysis_id IS NOT NULL"), sqlite_where=sa.text("status = 'open' AND analysis_id IS NOT NULL"))
    op.create_index('uq_position_symbol_open', 'positions', ['symbol'], unique=True, postgresql_where=sa.text("status = 'open' AND pair_group_id IS NULL"), sqlite_where=sa.text("status = 'open' AND pair_group_id IS NULL"))
    op.create_table('trade_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('priced_in_score', sa.Integer(), nullable=True),
    sa.Column('analysis_confidence', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holding_hours', sa.Float(), nullable=True),
    sa.Column('was_profitable', sa.Boolean(), nullable=True),
    sa.Column('was_debate_modified', sa.Boolean(), nullable=True),
    sa.Column('decision_source', sa.String(length=50), nullable=True),
    sa.Column('mae_pips', sa.Float(), nullable=True),
    sa.Column('mfe_pips', sa.Float(), nullable=True),
    sa.Column('sl_slippage_pips', sa.Float(), nullable=True),
    sa.Column('entry_session', sa.String(length=30), nullable=True),
    sa.Column('market_regime', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_outcome_closed', 'trade_outcomes', ['closed_at'], unique=False)
    op.create_index('idx_trade_outcome_profitable', 'trade_outcomes', ['was_profitable'], unique=False)
    op.create_index('idx_trade_outcome_symbol', 'trade_outcomes', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_analysis_id'), 'trade_outcomes', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_position_id'), 'trade_outcomes', ['position_id'], unique=False)
    op.create_table('trade_plan_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('leg_type', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('target_entry', sa.Float(), nullable=False),
    sa.Column('actual_entry', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['trade_plans.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_plan_leg_plan_status', 'trade_plan_legs', ['plan_id', 'status'], unique=False)
    op.create_index(op.f('ix_trade_plan_legs_plan_id'), 'trade_plan_legs', ['plan_id'], unique=False)
    op.create_table('llm_benchmark_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('judge_model', sa.String(length=160), nullable=False),
    sa.Column('reference_model', sa.String(length=160), nullable=False),
    sa.Column('tasks_json', sa.Text(), nullable=True),
    sa.Column('models_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_benchmark_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('context_key', sa.String(length=160), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_s', sa.Float(), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('deterministic_score', sa.Float(), nullable=True),
    sa.Column('judge_scores_json', sa.Text(), nullable=True),
    sa.Column('judge_overall', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['llm_benchmark_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_benchmark_result_model_name'), 'llm_benchmark_result', ['model_name'], unique=False)
    op.create_index(op.f('ix_llm_benchmark_result_run_id'), 'llm_benchmark_result', ['run_id'], unique=False)
    op.create_index(op.f('ix_llm_benchmark_result_task_id'), 'llm_benchmark_result', ['task_id'], unique=False)
    op.create_table('equity_drawdown_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('floating_pnl', sa.Float(), nullable=False),
    sa.Column('margin_level_pct', sa.Float(), nullable=True),
    sa.Column('drawdown_usd', sa.Float(), nullable=False),
    sa.Column('drawdown_pct', sa.Float(), nullable=False),
    sa.Column('peak_equity', sa.Float(), nullable=False),
    sa.Column('open_positions_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_equity_snapshot_ts', 'equity_drawdown_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_equity_drawdown_snapshots_timestamp'), 'equity_drawdown_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equity_drawdown_snapshots_timestamp'), table_name='equity_drawdown_snapshots')
    op.drop_index('idx_equity_snapshot_ts', table_name='equity_drawdown_snapshots')
    op.drop_table('equity_drawdown_snapshots')
    op.drop_index(op.f('ix_llm_benchmark_result_task_id'), table_name='llm_benchmark_result')
    op.drop_index(op.f('ix_llm_benchmark_result_run_id'), table_name='llm_benchmark_result')
    op.drop_index(op.f('ix_llm_benchmark_result_model_name'), table_name='llm_benchmark_result')
    op.drop_table('llm_benchmark_result')
    op.drop_table('llm_benchmark_run')
    op.drop_index(op.f('ix_trade_plan_legs_plan_id'), table_name='trade_plan_legs')
    op.drop_index('idx_trade_plan_leg_plan_status', table_name='trade_plan_legs')
    op.drop_table('trade_plan_legs')
    op.drop_index(op.f('ix_trade_outcomes_position_id'), table_name='trade_outcomes')
    op.drop_index(op.f('ix_trade_outcomes_analysis_id'), table_name='trade_outcomes')
    op.drop_index('idx_trade_outcome_symbol', table_name='trade_outcomes')
    op.drop_index('idx_trade_outcome_profitable', table_name='trade_outcomes')
    op.drop_index('idx_trade_outcome_closed', table_name='trade_outcomes')
    op.drop_table('trade_outcomes')
    op.drop_index('uq_position_symbol_open', table_name='positions', postgresql_where=sa.text("status = 'open' AND pair_group_id IS NULL"), sqlite_where=sa.text("status = 'open' AND pair_group_id IS NULL"))
    op.drop_index('uq_position_analysis_open', table_name='positions', postgresql_where=sa.text("status = 'open' AND analysis_id IS NOT NULL"), sqlite_where=sa.text("status = 'open' AND analysis_id IS NOT NULL"))
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_pair_group_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_order_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_analysis_id'), table_name='positions')
    op.drop_index('idx_position_status', table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('idx_cfo_symbol', table_name='confluence_factor_outcomes')
    op.drop_index('idx_cfo_outcome', table_name='confluence_factor_outcomes')
    op.drop_index('idx_cfo_factor', table_name='confluence_factor_outcomes')
    op.drop_table('confluence_factor_outcomes')
    op.drop_index(op.f('ix_trade_triggers_asset_analysis_id'), table_name='trade_triggers')
    op.drop_index('idx_trigger_status', table_name='trade_triggers')
    op.drop_table('trade_triggers')
    op.drop_index(op.f('ix_trade_plans_symbol'), table_name='trade_plans')
    op.drop_index(op.f('ix_trade_plans_status'), table_name='trade_plans')
    op.drop_index(op.f('ix_trade_plans_analysis_id'), table_name='trade_plans')
    op.drop_index('idx_trade_plan_symbol_status', table_name='trade_plans')
    op.drop_table('trade_plans')
    op.drop_index(op.f('ix_paper_trade_records_analysis_id'), table_name='paper_trade_records')
    op.drop_index('idx_paper_trade_symbol', table_name='paper_trade_records')
    op.drop_index('idx_paper_trade_status', table_name='paper_trade_records')
    op.drop_table('paper_trade_records')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_mt5_ticket'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_analysis_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_mt5_signals_symbol'), table_name='mt5_signals')
    op.drop_index(op.f('ix_mt5_signals_asset_analysis_id'), table_name='mt5_signals')
    op.drop_table('mt5_signals')
    op.drop_index(op.f('ix_decision_reflections_symbol'), table_name='decision_reflections')
    op.drop_index('idx_drefl_symbol_status', table_name='decision_reflections')
    op.drop_index('idx_drefl_paper', table_name='decision_reflections')
    op.drop_index('idx_drefl_fts', table_name='decision_reflections', postgresql_using='gin')
    op.drop_index('idx_drefl_created', table_name='decision_reflections')
    op.drop_table('decision_reflections')
    op.drop_index('idx_ncls_outcome_pending', table_name='news_classification_outcomes')
    op.drop_table('news_classification_outcomes')
    op.drop_table('backtest_trade')
    op.drop_index(op.f('ix_asset_analysis_symbol'), table_name='asset_analysis')
    op.drop_index(op.f('ix_asset_analysis_source_strategy_id'), table_name='asset_analysis')
    op.drop_index(op.f('ix_asset_analysis_pair_group_id'), table_name='asset_analysis')
    op.drop_index('idx_analysis_sym_date', table_name='asset_analysis')
    op.drop_table('asset_analysis')
    op.drop_table('vix_data')
    op.drop_index(op.f('ix_user_market_intel_telegram_user_id'), table_name='user_market_intel')
    op.drop_index(op.f('ix_user_market_intel_is_active'), table_name='user_market_intel')
    op.drop_index(op.f('ix_user_market_intel_expires_at'), table_name='user_market_intel')
    op.drop_index('ix_user_market_intel_active_exp', table_name='user_market_intel')
    op.drop_table('user_market_intel')
    op.drop_index('idx_treasury_tenor_date', table_name='treasury_yields')
    op.drop_table('treasury_yields')
    op.drop_index(op.f('ix_trading_state_logs_recorded_at'), table_name='trading_state_logs')
    op.drop_index(op.f('ix_trading_state_logs_cycle_id'), table_name='trading_state_logs')
    op.drop_index('idx_tslog_fts', table_name='trading_state_logs', postgresql_using='gin')
    op.drop_index('idx_tslog_cycle', table_name='trading_state_logs')
    op.drop_table('trading_state_logs')
    op.drop_index(op.f('ix_trading_events_ts_created'), table_name='trading_events')
    op.drop_index(op.f('ix_trading_events_seq'), table_name='trading_events')
    op.drop_index(op.f('ix_trading_events_event_type'), table_name='trading_events')
    op.drop_index(op.f('ix_trading_events_correlation_id'), table_name='trading_events')
    op.drop_table('trading_events')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_token_usage_log_timestamp'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_thinking_tokens'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_task_role'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_symbol'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_subsystem'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_status'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_cycle_id'), table_name='token_usage_log')
    op.drop_table('token_usage_log')
    op.drop_index(op.f('ix_timesfm_forecasts_symbol'), table_name='timesfm_forecasts')
    op.drop_index(op.f('ix_timesfm_forecasts_generated_at'), table_name='timesfm_forecasts')
    op.drop_index('idx_timesfm_sym_time', table_name='timesfm_forecasts')
    op.drop_table('timesfm_forecasts')
    op.drop_index(op.f('ix_telegram_topic_bindings_topic_id'), table_name='telegram_topic_bindings')
    op.drop_index(op.f('ix_telegram_topic_bindings_session_id'), table_name='telegram_topic_bindings')
    op.drop_index(op.f('ix_telegram_topic_bindings_chat_id'), table_name='telegram_topic_bindings')
    op.drop_index('idx_tg_topic_chat_topic', table_name='telegram_topic_bindings')
    op.drop_table('telegram_topic_bindings')
    op.drop_index(op.f('ix_telegram_conversations_telegram_user_id'), table_name='telegram_conversations')
    op.drop_index('idx_tg_user_timestamp', table_name='telegram_conversations')
    op.drop_table('telegram_conversations')
    op.drop_index('idx_indicator_sym_tf_ts', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_table('system_prompts')
    op.drop_table('system_config')
    op.drop_index('idx_swing_sym_tf', table_name='swing_points')
    op.drop_table('swing_points')
    op.drop_index('idx_sb_sym_tf', table_name='structure_breaks')
    op.drop_table('structure_breaks')
    op.drop_index('idx_sr_sym_tf', table_name='sr_zones')
    op.drop_table('sr_zones')
    op.drop_index(op.f('ix_risk_state_date'), table_name='risk_state')
    op.drop_table('risk_state')
    op.drop_index('idx_price_sym_tf_ts', table_name='price_ohlcv')
    op.drop_table('price_ohlcv')
    op.drop_index(op.f('ix_prescreen_log_symbol'), table_name='prescreen_log')
    op.drop_index('idx_prescreen_symbol_time', table_name='prescreen_log')
    op.drop_table('prescreen_log')
    op.drop_index(op.f('ix_playbook_rule_attributions_symbol'), table_name='playbook_rule_attributions')
    op.drop_index(op.f('ix_playbook_rule_attributions_status'), table_name='playbook_rule_attributions')
    op.drop_index(op.f('ix_playbook_rule_attributions_rule_hash'), table_name='playbook_rule_attributions')
    op.drop_index('idx_playbook_rule_sym_stat', table_name='playbook_rule_attributions')
    op.drop_table('playbook_rule_attributions')
    op.drop_index(op.f('ix_pattern_screening_cache_symbol'), table_name='pattern_screening_cache')
    op.drop_index(op.f('ix_pattern_screening_cache_screened_at'), table_name='pattern_screening_cache')
    op.drop_index('idx_pattern_cache_sym_at', table_name='pattern_screening_cache')
    op.drop_table('pattern_screening_cache')
    op.drop_table('orders_log')
    op.drop_index('idx_ob_sym_tf', table_name='order_blocks')
    op.drop_table('order_blocks')
    op.drop_index(op.f('ix_news_items_source'), table_name='news_items')
    op.drop_index('idx_news_url', table_name='news_items')
    op.drop_index('idx_news_source_fetched', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_news_digest_slices_period_start'), table_name='news_digest_slices')
    op.drop_index('ix_news_digest_slices_period', table_name='news_digest_slices')
    op.drop_table('news_digest_slices')
    op.drop_table('news_digest')
    op.drop_index(op.f('ix_market_chronicle_event_date'), table_name='market_chronicle')
    op.drop_index('idx_chronicle_fts', table_name='market_chronicle', postgresql_using='gin')
    op.drop_table('market_chronicle')
    op.drop_index('idx_liq_sym_tf', table_name='liquidity_zones')
    op.drop_table('liquidity_zones')
    op.drop_table('interest_rates')
    op.drop_index('idx_fvg_sym_tf', table_name='fvg_zones')
    op.drop_table('fvg_zones')
    op.drop_table('fundamental_briefs')
    op.drop_table('fedwatch_probabilities')
    op.drop_index(op.f('ix_economic_calendar_event_time'), table_name='economic_calendar')
    op.drop_index(op.f('ix_economic_calendar_currency'), table_name='economic_calendar')
    op.drop_table('economic_calendar')
    op.drop_table('dxy_data')
    op.drop_index(op.f('ix_decision_memory_backtest_run_id'), table_name='decision_memory_backtest')
    op.drop_table('decision_memory_backtest')
    op.drop_index(op.f('ix_cycle_performance_cycle_at'), table_name='cycle_performance')
    op.drop_table('cycle_performance')
    op.drop_index(op.f('ix_cycle_events_cycle_id'), table_name='cycle_events')
    op.drop_index('idx_cycle_event_type', table_name='cycle_events')
    op.drop_table('cycle_events')
    op.drop_index(op.f('ix_cot_report_market_code'), table_name='cot_report')
    op.drop_index('idx_cot_market_date', table_name='cot_report')
    op.drop_table('cot_report')
    op.drop_index(op.f('ix_context_spill_blobs_tool_name'), table_name='context_spill_blobs')
    op.drop_index(op.f('ix_context_spill_blobs_cycle_id'), table_name='context_spill_blobs')
    op.drop_index(op.f('ix_context_spill_blobs_created_at'), table_name='context_spill_blobs')
    op.drop_index(op.f('ix_context_spill_blobs_blob_id'), table_name='context_spill_blobs')
    op.drop_index('idx_spill_cycle_tool', table_name='context_spill_blobs')
    op.drop_table('context_spill_blobs')
    op.drop_index(op.f('ix_central_bank_rate_expectations_bank'), table_name='central_bank_rate_expectations')
    op.drop_index('idx_cb_rate_exp_bank_date', table_name='central_bank_rate_expectations')
    op.drop_table('central_bank_rate_expectations')
    op.drop_index(op.f('ix_candidate_lessons_symbol'), table_name='candidate_lessons')
    op.drop_index(op.f('ix_candidate_lessons_status'), table_name='candidate_lessons')
    op.drop_table('candidate_lessons')
    op.drop_index('idx_bond_yield_ct_date', table_name='bond_yield_data')
    op.drop_table('bond_yield_data')
    op.drop_table('backtest_run')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_parent_session_id'), table_name='agent_sessions')
    op.drop_index('idx_agent_sess_user_plat', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_agent_session_messages_session_id'), table_name='agent_session_messages')
    op.drop_index(op.f('ix_agent_session_messages_created_at'), table_name='agent_session_messages')
    op.drop_index(op.f('ix_agent_session_messages_compacted'), table_name='agent_session_messages')
    op.drop_index(op.f('ix_agent_session_messages_active'), table_name='agent_session_messages')
    op.drop_index('idx_asm_sess_created', table_name='agent_session_messages')
    op.drop_index('idx_asm_sess_active', table_name='agent_session_messages')
    op.drop_table('agent_session_messages')
    op.drop_index(op.f('ix_activity_log_timestamp'), table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
