"""add_paper_trade_entry_fields_and_confluence_factors

Revision ID: 01256fb545b3
Revises: cd3df75a8a1b
Create Date: 2026-08-11 15:37:29.913704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01256fb545b3'
down_revision: Union[str, Sequence[str], None] = 'cd3df75a8a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mt5_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_analysis_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mt5_ticket', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mt5_signals_symbol'), 'mt5_signals', ['symbol'], unique=False)
    op.add_column('asset_analysis', sa.Column('confluence_factors_json', sa.Text(), nullable=True))
    op.add_column('asset_analysis', sa.Column('execution_status', sa.String(length=20), nullable=True))
    op.add_column('asset_analysis', sa.Column('execution_notes', sa.Text(), nullable=True))
    op.add_column('asset_analysis', sa.Column('price_at_analysis', sa.Float(), nullable=True))
    op.add_column('asset_analysis', sa.Column('price_4h_after', sa.Float(), nullable=True))
    op.add_column('asset_analysis', sa.Column('price_24h_after', sa.Float(), nullable=True))
    op.add_column('asset_analysis', sa.Column('direction_correct_4h', sa.Boolean(), nullable=True))
    op.add_column('asset_analysis', sa.Column('direction_correct_24h', sa.Boolean(), nullable=True))
    op.add_column('paper_trade_records', sa.Column('entry_condition_type', sa.String(length=20), nullable=True))
    op.add_column('paper_trade_records', sa.Column('stated_entry_price', sa.Float(), nullable=True))
    op.add_column('paper_trade_records', sa.Column('is_pending_fill', sa.Boolean(), nullable=False))
    op.add_column('paper_trade_records', sa.Column('slippage_applied', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_trade_records', 'slippage_applied')
    op.drop_column('paper_trade_records', 'is_pending_fill')
    op.drop_column('paper_trade_records', 'stated_entry_price')
    op.drop_column('paper_trade_records', 'entry_condition_type')
    op.drop_column('asset_analysis', 'direction_correct_24h')
    op.drop_column('asset_analysis', 'direction_correct_4h')
    op.drop_column('asset_analysis', 'price_24h_after')
    op.drop_column('asset_analysis', 'price_4h_after')
    op.drop_column('asset_analysis', 'price_at_analysis')
    op.drop_column('asset_analysis', 'execution_notes')
    op.drop_column('asset_analysis', 'execution_status')
    op.drop_column('asset_analysis', 'confluence_factors_json')
    op.drop_index(op.f('ix_mt5_signals_symbol'), table_name='mt5_signals')
    op.drop_table('mt5_signals')
    # ### end Alembic commands ###
