"""add_structure_models

Revision ID: 22f055e65e0b
Revises: a1d26d0e92ee
Create Date: 2026-08-06 20:22:04.266207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f055e65e0b'
down_revision: Union[str, Sequence[str], None] = 'a1d26d0e92ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('price_high', sa.Float(), nullable=False),
    sa.Column('price_low', sa.Float(), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mitigated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ob_sym_tf', 'order_blocks', ['symbol', 'timeframe'], unique=False)
    op.create_table('structure_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sb_sym_tf', 'structure_breaks', ['symbol', 'timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sb_sym_tf', table_name='structure_breaks')
    op.drop_table('structure_breaks')
    op.drop_index('idx_ob_sym_tf', table_name='order_blocks')
    op.drop_table('order_blocks')
    # ### end Alembic commands ###
