"""Add market_regime_at_analysis

Revision ID: 2ec802a503b0
Revises: 45596ed8d1a4
Create Date: 2026-08-19 00:18:39.649422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec802a503b0'
down_revision: Union[str, Sequence[str], None] = '45596ed8d1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_analysis', sa.Column('market_regime_at_analysis', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_analysis', 'market_regime_at_analysis')
    # ### end Alembic commands ###
