"""Add detection_method to PaperTradeRecord

Revision ID: 4156a1f2790b
Revises: 4b3a90da55e9
Create Date: 2026-08-10 10:33:27.014277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4156a1f2790b'
down_revision: Union[str, Sequence[str], None] = '4b3a90da55e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_trade_records', sa.Column('detection_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_trade_records', 'detection_method')
    # ### end Alembic commands ###
