"""Add debate columns and profitable index

Revision ID: 45596ed8d1a4
Revises: 5195697e5d64
Create Date: 2026-08-18 15:03:40.830643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45596ed8d1a4'
down_revision: Union[str, Sequence[str], None] = '5195697e5d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_classification_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('symbol_checked', sa.String(length=20), nullable=False),
    sa.Column('classified_impact', sa.String(length=20), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_at_classification', sa.Float(), nullable=True),
    sa.Column('price_2h_after', sa.Float(), nullable=True),
    sa.Column('move_pct_2h', sa.Float(), nullable=True),
    sa.Column('outcome_matched_classification', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ncls_outcome_pending', 'news_classification_outcomes', ['checked_at', 'classified_at'], unique=False)
    op.add_column('decision_reflections', sa.Column('macro_thesis_correct', sa.Boolean(), nullable=True))
    op.add_column('fundamental_briefs', sa.Column('debate_bull_thesis', sa.Text(), nullable=True))
    op.add_column('fundamental_briefs', sa.Column('debate_bear_thesis', sa.Text(), nullable=True))
    op.add_column('fundamental_briefs', sa.Column('debate_winner', sa.String(length=20), nullable=True))
    op.add_column('fundamental_briefs', sa.Column('debate_escalation_required', sa.Boolean(), nullable=True))
    op.create_index('idx_trade_outcome_profitable', 'trade_outcomes', ['was_profitable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trade_outcome_profitable', table_name='trade_outcomes')
    op.drop_column('fundamental_briefs', 'debate_escalation_required')
    op.drop_column('fundamental_briefs', 'debate_winner')
    op.drop_column('fundamental_briefs', 'debate_bear_thesis')
    op.drop_column('fundamental_briefs', 'debate_bull_thesis')
    op.drop_column('decision_reflections', 'macro_thesis_correct')
    op.drop_index('idx_ncls_outcome_pending', table_name='news_classification_outcomes')
    op.drop_table('news_classification_outcomes')
    # ### end Alembic commands ###
