"""add_paper_trade_records

Revision ID: 4b3a90da55e9
Revises: b0fde765c72f
Create Date: 2026-08-08 14:10:02.169495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3a90da55e9'
down_revision: Union[str, Sequence[str], None] = 'b0fde765c72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trade_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('holding_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paper_trade_status', 'paper_trade_records', ['status'], unique=False)
    op.create_index('idx_paper_trade_symbol', 'paper_trade_records', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_paper_trade_symbol', table_name='paper_trade_records')
    op.drop_index('idx_paper_trade_status', table_name='paper_trade_records')
    op.drop_table('paper_trade_records')
    # ### end Alembic commands ###
