"""Sync database schema with current models

Revision ID: 5195697e5d64
Revises: c060f97f0f25
Create Date: 2026-08-18 11:10:15.582546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5195697e5d64'
down_revision: Union[str, Sequence[str], None] = 'c060f97f0f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_lifecycle_events_id'), table_name='plan_lifecycle_events')
    op.drop_index(op.f('ix_plan_lifecycle_events_plan_id'), table_name='plan_lifecycle_events')
    op.drop_index(op.f('ix_plan_lifecycle_events_timestamp'), table_name='plan_lifecycle_events')
    op.execute("DROP TABLE IF EXISTS plan_lifecycle_events CASCADE")
    op.drop_index(op.f('idx_wal_account'), table_name='wal_entries')
    op.drop_index(op.f('idx_wal_status'), table_name='wal_entries')
    op.drop_index(op.f('idx_wal_ticket'), table_name='wal_entries')
    op.drop_index(op.f('ix_wal_entries_account_number'), table_name='wal_entries')
    op.drop_index(op.f('ix_wal_entries_account_type'), table_name='wal_entries')
    op.drop_index(op.f('ix_wal_entries_created_at'), table_name='wal_entries')
    op.drop_index(op.f('ix_wal_entries_status'), table_name='wal_entries')
    op.drop_index(op.f('ix_wal_entries_ticket_id'), table_name='wal_entries')
    op.execute("DROP TABLE IF EXISTS wal_entries CASCADE")
    op.drop_index(op.f('ix_fedwatch_snapshots_created_at'), table_name='fedwatch_snapshots')
    op.execute("DROP TABLE IF EXISTS fedwatch_snapshots CASCADE")
    op.drop_index(op.f('ix_economic_event_outcomes_created_at'), table_name='economic_event_outcomes')
    op.drop_index(op.f('ix_economic_event_outcomes_currency'), table_name='economic_event_outcomes')
    op.drop_index(op.f('ix_economic_event_outcomes_event_hash'), table_name='economic_event_outcomes')
    op.execute("DROP TABLE IF EXISTS economic_event_outcomes CASCADE")
    op.drop_index(op.f('ix_real_yield_snapshots_created_at'), table_name='real_yield_snapshots')
    op.execute("DROP TABLE IF EXISTS real_yield_snapshots CASCADE")
    op.drop_index(op.f('ix_news_articles_is_processed'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_sumber'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_tanggal'), table_name='news_articles')
    op.execute("DROP TABLE IF EXISTS news_articles CASCADE")
    op.drop_index(op.f('ix_daily_equity_snapshots_account_number'), table_name='daily_equity_snapshots')
    op.drop_index(op.f('ix_daily_equity_snapshots_account_type'), table_name='daily_equity_snapshots')
    op.drop_index(op.f('ix_daily_equity_snapshots_date'), table_name='daily_equity_snapshots')
    op.execute("DROP TABLE IF EXISTS daily_equity_snapshots CASCADE")
    op.drop_index(op.f('ix_strat_asset_paradigm'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strat_duplicate_check'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strat_paradigm_status'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strat_status_asset'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_asset'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_dominant_regime'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_failed_pattern_hash'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_id'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_is_active'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_is_ai_generated'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_is_mfe_mae_ratio'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_is_pf'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_is_sqn'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_mc_robust'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_mc_score'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_mechanism'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_oos_expectancy'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_oos_mfe_mae_ratio'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_oos_pf'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_oos_robustness_pct'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_oos_sharpe_ratio'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_oos_sqn'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_slippage_tolerance_bps'), table_name='strategy_experiments')
    op.drop_index(op.f('ix_strategy_experiments_status'), table_name='strategy_experiments')
    op.execute("DROP TABLE IF EXISTS strategy_experiments CASCADE")
    op.execute("DROP TABLE IF EXISTS backtest_ledgers CASCADE")
    op.drop_index(op.f('ix_economic_events_event_hash'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_mata_uang'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_tanggal_waktu'), table_name='economic_events')
    op.execute("DROP TABLE IF EXISTS economic_events CASCADE")
    op.drop_index(op.f('ix_backtest_sessions_asset'), table_name='backtest_sessions')
    op.drop_index(op.f('ix_backtest_sessions_strategy_id'), table_name='backtest_sessions')
    op.execute("DROP TABLE IF EXISTS backtest_sessions CASCADE")
    op.drop_index(op.f('ix_ai_usage_logs_created_at'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_model'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_task'), table_name='ai_usage_logs')
    op.execute("DROP TABLE IF EXISTS ai_usage_logs CASCADE")
    op.drop_index(op.f('ix_ai_calibrated_metrics_asset'), table_name='ai_calibrated_metrics')
    op.drop_index(op.f('ix_ai_calibrated_metrics_created_at'), table_name='ai_calibrated_metrics')
    op.drop_index(op.f('ix_ai_calibrated_metrics_experiment_id'), table_name='ai_calibrated_metrics')
    op.execute("DROP TABLE IF EXISTS ai_calibrated_metrics CASCADE")
    op.drop_index(op.f('ix_trade_ledger_account_number'), table_name='trade_ledger')
    op.drop_index(op.f('ix_trade_ledger_account_type'), table_name='trade_ledger')
    op.drop_index(op.f('ix_trade_ledger_asset'), table_name='trade_ledger')
    op.drop_index(op.f('ix_trade_ledger_close_time'), table_name='trade_ledger')
    op.drop_index(op.f('ix_trade_ledger_ticket'), table_name='trade_ledger')
    op.execute("DROP TABLE IF EXISTS trade_ledger CASCADE")
    op.drop_index(op.f('ix_plan_evaluations_id'), table_name='plan_evaluations')
    op.execute("DROP TABLE IF EXISTS plan_evaluations CASCADE")
    op.drop_index(op.f('ix_twitter_live_squawk_is_processed'), table_name='twitter_live_squawk')
    op.drop_index(op.f('ix_twitter_live_squawk_username'), table_name='twitter_live_squawk')
    op.drop_index(op.f('ix_twitter_live_squawk_waktu'), table_name='twitter_live_squawk')
    op.execute("DROP TABLE IF EXISTS twitter_live_squawk CASCADE")
    op.drop_index(op.f('ix_price_reaction_logs_asset'), table_name='price_reaction_logs')
    op.drop_index(op.f('ix_price_reaction_logs_level_type'), table_name='price_reaction_logs')
    op.drop_index(op.f('ix_price_reaction_logs_timestamp_ms'), table_name='price_reaction_logs')
    op.execute("DROP TABLE IF EXISTS price_reaction_logs CASCADE")
    op.drop_index(op.f('ix_trading_plans_account_number'), table_name='trading_plans')
    op.drop_index(op.f('ix_trading_plans_account_type'), table_name='trading_plans')
    op.drop_index(op.f('ix_trading_plans_asset'), table_name='trading_plans')
    op.drop_index(op.f('ix_trading_plans_id'), table_name='trading_plans')
    op.drop_index(op.f('ix_trading_plans_is_active'), table_name='trading_plans')
    op.drop_index(op.f('ix_trading_plans_magic_number'), table_name='trading_plans')
    op.drop_index(op.f('ix_trading_plans_status'), table_name='trading_plans')
    op.drop_index(op.f('ix_trading_plans_strategy_id'), table_name='trading_plans')
    op.drop_index(op.f('ix_trading_plans_trading_paradigm'), table_name='trading_plans')
    op.execute("DROP TABLE IF EXISTS trading_plans CASCADE")
    op.drop_index(op.f('ix_macro_analysis_states_created_at'), table_name='macro_analysis_states')
    op.execute("DROP TABLE IF EXISTS macro_analysis_states CASCADE")
    op.add_column('asset_analysis', sa.Column('specialist_biases_json', sa.Text(), nullable=True))
    op.add_column('asset_analysis', sa.Column('risk_multiplier', sa.Float(), nullable=True))
    op.add_column('asset_analysis', sa.Column('debate_bull_thesis', sa.Text(), nullable=True))
    op.add_column('asset_analysis', sa.Column('debate_bear_dissent', sa.Text(), nullable=True))
    op.add_column('asset_analysis', sa.Column('debate_verdict', sa.String(length=50), nullable=True))
    op.add_column('asset_analysis', sa.Column('debate_reason', sa.Text(), nullable=True))
    op.add_column('asset_analysis', sa.Column('decision_source', sa.String(length=50), nullable=True))
    op.add_column('asset_analysis', sa.Column('was_debate_modified', sa.Boolean(), nullable=True))
    op.add_column('asset_analysis', sa.Column('was_ssvp_suppressed', sa.Boolean(), nullable=True))
    op.drop_index(op.f('idx_asset_analysis_cds'), table_name='asset_analysis', postgresql_where='(ssvp_cds_score_at_analysis IS NOT NULL)')
    op.add_column('decision_reflections', sa.Column('next_trade_adjustment', sa.Text(), nullable=True))
    op.add_column('decision_reflections', sa.Column('specific_lesson', sa.Text(), nullable=True))
    op.add_column('decision_reflections', sa.Column('process_was_sound', sa.Boolean(), nullable=True))
    op.add_column('decision_reflections', sa.Column('outcome_process_classification', sa.String(length=50), nullable=True))
    op.alter_column('decision_reflections', 'is_context_contaminated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_drefl_contaminated'), table_name='decision_reflections')
    op.create_index(op.f('ix_decision_reflections_symbol'), 'decision_reflections', ['symbol'], unique=False)
    op.add_column('paper_trade_records', sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('paper_trade_records', sa.Column('decision_source', sa.String(length=50), nullable=True))
    op.add_column('paper_trade_records', sa.Column('was_debate_modified', sa.Boolean(), nullable=True))
    op.add_column('paper_trade_records', sa.Column('was_ssvp_suppressed', sa.Boolean(), nullable=True))
    op.alter_column('system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_syscfg_ssvp'), table_name='system_config', postgresql_where="((key)::text ~~ 'ssvp_cds_%'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_syscfg_ssvp'), 'system_config', ['key'], unique=False, postgresql_where="((key)::text ~~ 'ssvp_cds_%'::text)")
    op.alter_column('system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('paper_trade_records', 'was_ssvp_suppressed')
    op.drop_column('paper_trade_records', 'was_debate_modified')
    op.drop_column('paper_trade_records', 'decision_source')
    op.drop_column('paper_trade_records', 'filled_at')
    op.drop_index(op.f('ix_decision_reflections_symbol'), table_name='decision_reflections')
    op.create_index(op.f('idx_drefl_contaminated'), 'decision_reflections', ['is_context_contaminated', 'symbol'], unique=False)
    op.alter_column('decision_reflections', 'is_context_contaminated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('decision_reflections', 'outcome_process_classification')
    op.drop_column('decision_reflections', 'process_was_sound')
    op.drop_column('decision_reflections', 'specific_lesson')
    op.drop_column('decision_reflections', 'next_trade_adjustment')
    op.create_index(op.f('idx_asset_analysis_cds'), 'asset_analysis', ['ssvp_cds_score_at_analysis'], unique=False, postgresql_where='(ssvp_cds_score_at_analysis IS NOT NULL)')
    op.drop_column('asset_analysis', 'was_ssvp_suppressed')
    op.drop_column('asset_analysis', 'was_debate_modified')
    op.drop_column('asset_analysis', 'decision_source')
    op.drop_column('asset_analysis', 'debate_reason')
    op.drop_column('asset_analysis', 'debate_verdict')
    op.drop_column('asset_analysis', 'debate_bear_dissent')
    op.drop_column('asset_analysis', 'debate_bull_thesis')
    op.drop_column('asset_analysis', 'risk_multiplier')
    op.drop_column('asset_analysis', 'specialist_biases_json')
    op.create_table('macro_analysis_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('executive_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sentiment_narrative', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vix_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cme_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fundamentals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('structured_memory', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('real_yield_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rate_differentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('macro_analysis_states_pkey'))
    )
    op.create_index(op.f('ix_macro_analysis_states_created_at'), 'macro_analysis_states', ['created_at'], unique=False)
    op.create_table('trading_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeframe_anchor', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('bias_direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('offensive_ast', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('defensive_ast', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('thought_process', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('offensive_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('defensive_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_zone_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_zone_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stop_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('take_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'EXECUTED', 'EXPIRED', 'CLOSED', 'PROFIT', 'LOSS', 'CANCELLED', 'PENDING_CLOSE', 'FAILED', 'WAIT', 'WAIT_DIRECTION', 'WAIT_LEVEL', 'READY_LIMIT', 'PENDING_REVIEW', name='planstatus'), autoincrement=False, nullable=False),
    sa.Column('is_executed_by_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ai_rationale', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_evaluated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('kelly_fraction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mt5_ticket', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('max_holding_bars', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trading_paradigm', sa.VARCHAR(length=20), server_default=sa.text("'swing'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('realized_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('initial_sl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('initial_tp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_execution_policy', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('executed_at_msc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('entry_zone_reached_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejection_log', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('eqs_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_v2_plan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('viable_regimes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Regime pasar di mana strategi valid'),
    sa.Column('wait_trigger_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wait_monitoring_levels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('wait_invalidation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wait_expected_bars', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('wait_spec_full', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('executed_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=10), server_default=sa.text("'DEMO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('magic_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('creation_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Konteks makro, teknikal, dan harga saat plan dibuat'),
    sa.Column('post_mortem_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Evaluasi mendalam AI setelah plan berakhir'),
    sa.Column('is_modified_by_user', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('user_modification_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_ai_plan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('review_deadline_ms', sa.BIGINT(), autoincrement=False, nullable=True, comment='Epoch ms kapan PENDING_REVIEW plan expire jika belum di-review user'),
    sa.Column('user_review_note', sa.TEXT(), autoincrement=False, nullable=True, comment='Catatan/alasan dari user saat review (approve/modify/reject)'),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp saat user melakukan review'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_experiments.id'], name=op.f('trading_plans_strategy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trading_plans_pkey'))
    )
    op.create_index(op.f('ix_trading_plans_trading_paradigm'), 'trading_plans', ['trading_paradigm'], unique=False)
    op.create_index(op.f('ix_trading_plans_strategy_id'), 'trading_plans', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trading_plans_status'), 'trading_plans', ['status'], unique=False)
    op.create_index(op.f('ix_trading_plans_magic_number'), 'trading_plans', ['magic_number'], unique=False)
    op.create_index(op.f('ix_trading_plans_is_active'), 'trading_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_trading_plans_id'), 'trading_plans', ['id'], unique=False)
    op.create_index(op.f('ix_trading_plans_asset'), 'trading_plans', ['asset'], unique=False)
    op.create_index(op.f('ix_trading_plans_account_type'), 'trading_plans', ['account_type'], unique=False)
    op.create_index(op.f('ix_trading_plans_account_number'), 'trading_plans', ['account_number'], unique=False)
    op.create_table('price_reaction_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('level_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reaction_magnitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume_at_reaction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oscillator_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ema_context', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('paradigm_window', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('quantitative_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('price_reaction_logs_pkey'))
    )
    op.create_index(op.f('ix_price_reaction_logs_timestamp_ms'), 'price_reaction_logs', ['timestamp_ms'], unique=False)
    op.create_index(op.f('ix_price_reaction_logs_level_type'), 'price_reaction_logs', ['level_type'], unique=False)
    op.create_index(op.f('ix_price_reaction_logs_asset'), 'price_reaction_logs', ['asset'], unique=False)
    op.create_table('twitter_live_squawk',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('waktu', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('translated_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('information_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alpha_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_institutional_source', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('contradicts_consensus', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('market_impact_timeframe', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('affected_currencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('narrative_arc_position', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('central_bank_signal_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('narrative_chain_assessment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_data_point_extracted', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('regime_shift_signal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('twitter_live_squawk_pkey')),
    sa.UniqueConstraint('url', name=op.f('twitter_live_squawk_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_twitter_live_squawk_waktu'), 'twitter_live_squawk', ['waktu'], unique=False)
    op.create_index(op.f('ix_twitter_live_squawk_username'), 'twitter_live_squawk', ['username'], unique=False)
    op.create_index(op.f('ix_twitter_live_squawk_is_processed'), 'twitter_live_squawk', ['is_processed'], unique=False)
    op.create_table('plan_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evaluation_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('thought_process', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_recommendation', postgresql.ENUM('HOLD', 'CLOSE', 'MOVE_SL', 'PARTIAL_CLOSE', 'WAIT_AND_SEE', name='airecommendationenum'), autoincrement=False, nullable=False),
    sa.Column('ai_reasoning', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['trading_plans.id'], name=op.f('plan_evaluations_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_evaluations_pkey'))
    )
    op.create_index(op.f('ix_plan_evaluations_id'), 'plan_evaluations', ['id'], unique=False)
    op.create_table('trade_ledger',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('asset', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('order_type', postgresql.ENUM('BUY', 'SELL', 'BUY_LIMIT', 'SELL_LIMIT', 'BUY_STOP', 'SELL_STOP', name='ordertypeenum'), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gross_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('commission', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('swap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mfe_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mae_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('holding_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exit_reason', postgresql.ENUM('SL_HIT', 'TP_HIT', 'TRAILING_SL', 'TIME_EXIT', 'MANUAL_CLOSE', 'META_REGIME_KILL', 'RUST_AUTO_CLOSE', 'UNKNOWN', '3D_REGIME_KILL', 'PRE_EMPTIVE_KILL', 'SPREAD_VACUUM_ESCAPE', 'MICRO_TOXIC_FLOW_ESCAPE', 'TOXIC_FLOW_ESCAPE', 'DAEMON_SYNC_CLOSE', 'DAEMON_CLOSE_SYNC', 'SL_TP_REJECT_FAILSAFE', 'REGIME_3D_KILL', 'SL_TP_HIT', 'RECOVERY_SYNC_CLOSE', name='exitreasonenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('entry_regime', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('initial_sl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('initial_tp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_sl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_tp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('signal_to_fill_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expected_entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('slippage_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_regime', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('account_balance_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eqs_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=10), server_default=sa.text("'DEMO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['trading_plans.id'], name=op.f('trade_ledger_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_ledger_pkey'))
    )
    op.create_index(op.f('ix_trade_ledger_ticket'), 'trade_ledger', ['ticket'], unique=True)
    op.create_index(op.f('ix_trade_ledger_close_time'), 'trade_ledger', ['close_time'], unique=False)
    op.create_index(op.f('ix_trade_ledger_asset'), 'trade_ledger', ['asset'], unique=False)
    op.create_index(op.f('ix_trade_ledger_account_type'), 'trade_ledger', ['account_type'], unique=False)
    op.create_index(op.f('ix_trade_ledger_account_number'), 'trade_ledger', ['account_number'], unique=False)
    op.create_table('ai_calibrated_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('critic_score_is', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('critic_decision_is', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('oos_passed_windows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oos_total_windows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oos_success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('live_win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('live_trade_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('live_pf', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('asset', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('paradigm', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('execution_tf', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['strategy_experiments.id'], name=op.f('ai_calibrated_metrics_experiment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_calibrated_metrics_pkey'))
    )
    op.create_index(op.f('ix_ai_calibrated_metrics_experiment_id'), 'ai_calibrated_metrics', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_ai_calibrated_metrics_created_at'), 'ai_calibrated_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_calibrated_metrics_asset'), 'ai_calibrated_metrics', ['asset'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key_idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thinking_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_usage_logs_pkey'))
    )
    op.create_index(op.f('ix_ai_usage_logs_task'), 'ai_usage_logs', ['task'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_model'), 'ai_usage_logs', ['model'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_created_at'), 'ai_usage_logs', ['created_at'], unique=False)
    op.create_table('backtest_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('initial_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('risk_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('final_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sizing_method', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('kelly_fraction_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_experiments.id'], name=op.f('backtest_sessions_strategy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('backtest_sessions_pkey'))
    )
    op.create_index(op.f('ix_backtest_sessions_strategy_id'), 'backtest_sessions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtest_sessions_asset'), 'backtest_sessions', ['asset'], unique=False)
    op.create_table('economic_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tanggal_waktu', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('mata_uang', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('impact', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('judul_event', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('forecast', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('previous', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('actual', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('surprise_sigma', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Deviasi standar dari konsensus'),
    sa.Column('is_high_impact', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_data_released', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('composite_impact_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='0-10 score gabungan impact+sigma'),
    sa.PrimaryKeyConstraint('id', name=op.f('economic_events_pkey'))
    )
    op.create_index(op.f('ix_economic_events_tanggal_waktu'), 'economic_events', ['tanggal_waktu'], unique=False)
    op.create_index(op.f('ix_economic_events_mata_uang'), 'economic_events', ['mata_uang'], unique=False)
    op.create_index(op.f('ix_economic_events_event_hash'), 'economic_events', ['event_hash'], unique=True)
    op.create_table('backtest_ledgers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trade_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('mfe_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mae_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('commission', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('duration_bars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exit_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['backtest_sessions.id'], name=op.f('backtest_ledgers_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('backtest_ledgers_pkey'))
    )
    op.create_table('strategy_experiments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generation_depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_pattern_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('is_ai_generated', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('mechanism', sa.VARCHAR(length=50), server_default=sa.text("'UNKNOWN'::character varying"), autoincrement=False, nullable=False),
    sa.Column('asset', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trading_paradigm', sa.VARCHAR(length=20), server_default=sa.text("'swing'::character varying"), autoincrement=False, nullable=False),
    sa.Column('screening_timeframe', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('execution_timeframe', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('hypothesis', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mutation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_reflection_memory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('offensive_ast', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('defensive_ast', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('stop_loss_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('take_profit_rr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('use_trailing_stop', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('trailing_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_holding_bars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trading_hours_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trading_hours_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dominant_regime', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('viable_regimes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_regime_specialist', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('kelly_fraction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('optimal_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cusum_stat', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('cusum_alert', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_paper_trading', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('NEEDS_IMPROVEMENT', 'NEEDS_FURTHER_TESTING', 'VERIFIED', 'TOTAL_FAILURE', 'MUTATED', 'PENDING', name='strategystatus'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_production_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('production_locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rolling_window_computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('in_sample_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('oos_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('regime_performance_map', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('oos_regime_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mae_mfe_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_attribute_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mc_robust', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('mc_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slippage_tolerance_bps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trade_frequency_per_month', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_win_duration_bars', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_loss_duration_bars', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_pf', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_winrate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_max_dd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_expectancy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_sqn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_sharpe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_calmar_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_pnl_skewness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_mfe_mae_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_max_consecutive_losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oos_pf', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_winrate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_max_dd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oos_robustness_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_expectancy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_sqn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_sharpe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_calmar_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_pnl_skewness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_max_consecutive_losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oos_mfe_mae_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_avg_duration_bars', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_trade_frequency_per_month', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('evolution_trajectory', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('live_trade_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('excluded_regimes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['strategy_experiments.id'], name=op.f('strategy_experiments_parent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('strategy_experiments_pkey'))
    )
    op.create_index(op.f('ix_strategy_experiments_status'), 'strategy_experiments', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_slippage_tolerance_bps'), 'strategy_experiments', ['slippage_tolerance_bps'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_oos_sqn'), 'strategy_experiments', ['oos_sqn'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_oos_sharpe_ratio'), 'strategy_experiments', ['oos_sharpe_ratio'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_oos_robustness_pct'), 'strategy_experiments', ['oos_robustness_pct'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_oos_pf'), 'strategy_experiments', ['oos_pf'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_oos_mfe_mae_ratio'), 'strategy_experiments', ['oos_mfe_mae_ratio'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_oos_expectancy'), 'strategy_experiments', ['oos_expectancy'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_mechanism'), 'strategy_experiments', ['mechanism'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_mc_score'), 'strategy_experiments', ['mc_score'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_mc_robust'), 'strategy_experiments', ['mc_robust'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_is_sqn'), 'strategy_experiments', ['is_sqn'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_is_pf'), 'strategy_experiments', ['is_pf'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_is_mfe_mae_ratio'), 'strategy_experiments', ['is_mfe_mae_ratio'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_is_ai_generated'), 'strategy_experiments', ['is_ai_generated'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_is_active'), 'strategy_experiments', ['is_active'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_id'), 'strategy_experiments', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_failed_pattern_hash'), 'strategy_experiments', ['failed_pattern_hash'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_dominant_regime'), 'strategy_experiments', ['dominant_regime'], unique=False)
    op.create_index(op.f('ix_strategy_experiments_asset'), 'strategy_experiments', ['asset'], unique=False)
    op.create_index(op.f('ix_strat_status_asset'), 'strategy_experiments', ['status', 'asset'], unique=False)
    op.create_index(op.f('ix_strat_paradigm_status'), 'strategy_experiments', ['trading_paradigm', 'status'], unique=False)
    op.create_index(op.f('ix_strat_duplicate_check'), 'strategy_experiments', ['failed_pattern_hash', 'asset', 'execution_timeframe', 'trading_paradigm'], unique=False)
    op.create_index(op.f('ix_strat_asset_paradigm'), 'strategy_experiments', ['asset', 'trading_paradigm'], unique=False)
    op.create_table('daily_equity_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('equity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('margin_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('daily_realized_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=10), server_default=sa.text("'DEMO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_equity_snapshots_pkey'))
    )
    op.create_index(op.f('ix_daily_equity_snapshots_date'), 'daily_equity_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_daily_equity_snapshots_account_type'), 'daily_equity_snapshots', ['account_type'], unique=False)
    op.create_index(op.f('ix_daily_equity_snapshots_account_number'), 'daily_equity_snapshots', ['account_number'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tanggal', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sumber', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('judul', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('indonesian_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alpha_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('information_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('impact_horizon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('market_psychology', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('asset_vector_bias', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('economic_surprise_sigma', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('impact_duration_estimate', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('primary_affected_pair', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('correlated_assets_affected', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('revision_from_previous', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('central_bank_bias_shift', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_likely_priced_in', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_institutional_event', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('composite_news_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Composite dari alpha_score * tier_weight * (1 + |sigma|/3)'),
    sa.Column('affected_currencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('narrative_arc_position', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('implicit_policy_signal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inter_news_relationship', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_number_extracted', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('news_articles_pkey')),
    sa.UniqueConstraint('url', name=op.f('news_articles_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_news_articles_tanggal'), 'news_articles', ['tanggal'], unique=False)
    op.create_index(op.f('ix_news_articles_sumber'), 'news_articles', ['sumber'], unique=False)
    op.create_index(op.f('ix_news_articles_is_processed'), 'news_articles', ['is_processed'], unique=False)
    op.create_table('real_yield_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('us_10y_real_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('us_5y_real_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('us_10y_breakeven', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hy_spread', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ig_spread', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gdpnow_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rate_differentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('gold_signal', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('credit_regime', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('real_yield_snapshots_pkey'))
    )
    op.create_index(op.f('ix_real_yield_snapshots_created_at'), 'real_yield_snapshots', ['created_at'], unique=False)
    op.create_table('economic_event_outcomes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('surprise_sigma', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('impact', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('price_before', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price_1h_after', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price_4h_after', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price_move_1h', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price_move_4h', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('vix_at_release', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_session', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('revision_from_previous', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('primary_pair_direction_1h', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('primary_pair_pct_move_1h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_hash'], ['economic_events.event_hash'], name=op.f('economic_event_outcomes_event_hash_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('economic_event_outcomes_pkey'))
    )
    op.create_index(op.f('ix_economic_event_outcomes_event_hash'), 'economic_event_outcomes', ['event_hash'], unique=False)
    op.create_index(op.f('ix_economic_event_outcomes_currency'), 'economic_event_outcomes', ['currency'], unique=False)
    op.create_index(op.f('ix_economic_event_outcomes_created_at'), 'economic_event_outcomes', ['created_at'], unique=False)
    op.create_table('fedwatch_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('data_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('fedwatch_snapshots_pkey'))
    )
    op.create_index(op.f('ix_fedwatch_snapshots_created_at'), 'fedwatch_snapshots', ['created_at'], unique=False)
    op.create_table('wal_entries',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING_EXECUTION'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=10), server_default=sa.text("'DEMO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('wal_entries_pkey'))
    )
    op.create_index(op.f('ix_wal_entries_ticket_id'), 'wal_entries', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_wal_entries_status'), 'wal_entries', ['status'], unique=False)
    op.create_index(op.f('ix_wal_entries_created_at'), 'wal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_wal_entries_account_type'), 'wal_entries', ['account_type'], unique=False)
    op.create_index(op.f('ix_wal_entries_account_number'), 'wal_entries', ['account_number'], unique=False)
    op.create_index(op.f('idx_wal_ticket'), 'wal_entries', ['ticket_id'], unique=False)
    op.create_index(op.f('idx_wal_status'), 'wal_entries', ['status', 'created_at'], unique=False)
    op.create_index(op.f('idx_wal_account'), 'wal_entries', ['account_number', 'account_type'], unique=False)
    op.create_table('plan_lifecycle_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('CREATED', 'APPROACHING_ENTRY', 'REACHED_ENTRY', 'REJECTED_BY_GATEKEEPER', 'MOVED_AWAY', 'CONDITION_CHANGED', 'EXECUTED', 'SL_HIT', 'TP_HIT', 'CLOSED', 'EXPIRED', 'MANUAL_CANCEL', name='lifecycleeventtype'), autoincrement=False, nullable=False),
    sa.Column('price_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['trading_plans.id'], name=op.f('plan_lifecycle_events_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_lifecycle_events_pkey'))
    )
    op.create_index(op.f('ix_plan_lifecycle_events_timestamp'), 'plan_lifecycle_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_plan_lifecycle_events_plan_id'), 'plan_lifecycle_events', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_lifecycle_events_id'), 'plan_lifecycle_events', ['id'], unique=False)
    # ### end Alembic commands ###
