"""add_systemconfig_description

Revision ID: 6b415f7529f6
Revises: 0dc17a9c300a
Create Date: 2026-08-16 13:22:11.373472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b415f7529f6'
down_revision: Union[str, Sequence[str], None] = '0dc17a9c300a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('system_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'updated_at')
    op.drop_column('system_config', 'description')
    # ### end Alembic commands ###
