"""Add TradeOutcome

Revision ID: 7da1dc0bfedc
Revises: 8e1f0b3ad7a5
Create Date: 2026-08-08 13:00:08.577704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da1dc0bfedc'
down_revision: Union[str, Sequence[str], None] = '8e1f0b3ad7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('news_scraped', sa.Integer(), nullable=False),
    sa.Column('calendar_scraped', sa.Integer(), nullable=False),
    sa.Column('stage1_success', sa.Boolean(), nullable=False),
    sa.Column('stage1_tokens_in', sa.Integer(), nullable=False),
    sa.Column('stage1_tokens_out', sa.Integer(), nullable=False),
    sa.Column('assets_analyzed', sa.Integer(), nullable=False),
    sa.Column('assets_skipped', sa.Integer(), nullable=False),
    sa.Column('decisions_buy', sa.Integer(), nullable=False),
    sa.Column('decisions_sell', sa.Integer(), nullable=False),
    sa.Column('decisions_wait', sa.Integer(), nullable=False),
    sa.Column('decisions_avoid', sa.Integer(), nullable=False),
    sa.Column('stage2_tokens_in', sa.Integer(), nullable=False),
    sa.Column('stage2_tokens_out', sa.Integer(), nullable=False),
    sa.Column('trades_proposed', sa.Integer(), nullable=False),
    sa.Column('trades_executed', sa.Integer(), nullable=False),
    sa.Column('trades_blocked', sa.Integer(), nullable=False),
    sa.Column('api_cost_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_performance_cycle_at'), 'cycle_performance', ['cycle_at'], unique=False)
    op.create_table('trade_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('priced_in_score', sa.Integer(), nullable=True),
    sa.Column('analysis_confidence', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holding_hours', sa.Float(), nullable=True),
    sa.Column('was_profitable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_outcome_closed', 'trade_outcomes', ['closed_at'], unique=False)
    op.create_index('idx_trade_outcome_symbol', 'trade_outcomes', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trade_outcome_symbol', table_name='trade_outcomes')
    op.drop_index('idx_trade_outcome_closed', table_name='trade_outcomes')
    op.drop_table('trade_outcomes')
    op.drop_index(op.f('ix_cycle_performance_cycle_at'), table_name='cycle_performance')
    op.drop_table('cycle_performance')
    # ### end Alembic commands ###
