"""Add confidence and risk_sentiment to FundamentalBrief

Revision ID: 80efc7b9ba45
Revises: b7045c4e0a72
Create Date: 2026-08-07 16:18:07.461812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80efc7b9ba45'
down_revision: Union[str, Sequence[str], None] = 'b7045c4e0a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_briefs', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('fundamental_briefs', sa.Column('risk_sentiment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_briefs', 'risk_sentiment')
    op.drop_column('fundamental_briefs', 'confidence')
    # ### end Alembic commands ###
