"""add_priced_in_override_justification

Revision ID: 88b6f559ecd1
Revises: 01256fb545b3
Create Date: 2026-08-13 22:40:58.758299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b6f559ecd1'
down_revision: Union[str, Sequence[str], None] = '01256fb545b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confluence_factor_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_trade_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('factor_name', sa.String(length=50), nullable=False),
    sa.Column('was_present', sa.Boolean(), nullable=False),
    sa.Column('trade_outcome', sa.String(length=20), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['asset_analysis.id'], ),
    sa.ForeignKeyConstraint(['paper_trade_id'], ['paper_trade_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cfo_factor', 'confluence_factor_outcomes', ['factor_name'], unique=False)
    op.create_index('idx_cfo_outcome', 'confluence_factor_outcomes', ['trade_outcome'], unique=False)
    op.create_index('idx_cfo_symbol', 'confluence_factor_outcomes', ['symbol'], unique=False)
    op.add_column('asset_analysis', sa.Column('priced_in_override_justification', sa.Text(), nullable=True))
    op.add_column('cycle_performance', sa.Column('health_score', sa.Float(), nullable=True))
    op.add_column('cycle_performance', sa.Column('data_completeness_score', sa.Float(), nullable=True))
    op.add_column('cycle_performance', sa.Column('tool_success_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycle_performance', 'tool_success_rate')
    op.drop_column('cycle_performance', 'data_completeness_score')
    op.drop_column('cycle_performance', 'health_score')
    op.drop_column('asset_analysis', 'priced_in_override_justification')
    op.drop_index('idx_cfo_symbol', table_name='confluence_factor_outcomes')
    op.drop_index('idx_cfo_outcome', table_name='confluence_factor_outcomes')
    op.drop_index('idx_cfo_factor', table_name='confluence_factor_outcomes')
    op.drop_table('confluence_factor_outcomes')
    # ### end Alembic commands ###
