"""add_priced_in_score_confluence_score_to_asset_analysis

Revision ID: 8e1f0b3ad7a5
Revises: 92900d8da723
Create Date: 2026-08-08 09:26:54.065922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1f0b3ad7a5'
down_revision: Union[str, Sequence[str], None] = '92900d8da723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_analysis', sa.Column('priced_in_score', sa.Integer(), nullable=True))
    op.add_column('asset_analysis', sa.Column('confluence_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_analysis', 'confluence_score')
    op.drop_column('asset_analysis', 'priced_in_score')
    # ### end Alembic commands ###
