"""add_confidence_to_fundamental_brief

Revision ID: 92900d8da723
Revises: 80efc7b9ba45
Create Date: 2026-08-07 16:29:22.210188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92900d8da723'
down_revision: Union[str, Sequence[str], None] = '80efc7b9ba45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
