"""initial_schema

Revision ID: 9c013c8f495b
Revises: 
Create Date: 2026-08-06 19:22:28.468065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c013c8f495b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_timestamp'), 'activity_log', ['timestamp'], unique=False)
    op.create_table('cot_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_code', sa.String(length=20), nullable=False),
    sa.Column('dealer_long', sa.Integer(), nullable=False),
    sa.Column('dealer_short', sa.Integer(), nullable=False),
    sa.Column('asset_mgr_long', sa.Integer(), nullable=False),
    sa.Column('asset_mgr_short', sa.Integer(), nullable=False),
    sa.Column('leveraged_long', sa.Integer(), nullable=False),
    sa.Column('leveraged_short', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cot_market_date', 'cot_report', ['market_code', 'report_date'], unique=False)
    op.create_index(op.f('ix_cot_report_market_code'), 'cot_report', ['market_code'], unique=False)
    op.create_table('dxy_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('economic_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('actual', sa.String(length=50), nullable=True),
    sa.Column('forecast', sa.String(length=50), nullable=True),
    sa.Column('previous', sa.String(length=50), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('surprise_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_calendar_currency'), 'economic_calendar', ['currency'], unique=False)
    op.create_index(op.f('ix_economic_calendar_event_time'), 'economic_calendar', ['event_time'], unique=False)
    op.create_table('fedwatch_probabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.String(length=20), nullable=False),
    sa.Column('probabilities_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fundamental_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('structured_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fvg_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('gap_high', sa.Float(), nullable=False),
    sa.Column('gap_low', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fvg_sym_tf', 'fvg_zones', ['symbol', 'timeframe'], unique=False)
    op.create_table('interest_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=20), nullable=False),
    sa.Column('rate_percent', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_meeting_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidity_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('zone_high', sa.Float(), nullable=False),
    sa.Column('zone_low', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('identified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_liq_sym_tf', 'liquidity_zones', ['symbol', 'timeframe'], unique=False)
    op.create_table('news_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_hours', sa.Integer(), nullable=False),
    sa.Column('digest_text', sa.Text(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency_tags', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gemini_impact', sa.String(length=20), nullable=True),
    sa.Column('gemini_sentiment', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_source_fetched', 'news_items', ['source', 'fetched_at'], unique=False)
    op.create_index('idx_news_url', 'news_items', ['url'], unique=False)
    op.create_index(op.f('ix_news_items_source'), 'news_items', ['source'], unique=False)
    op.create_table('orders_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mt5_ticket', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_ticket')
    )
    op.create_index('idx_position_status', 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('price_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_price_sym_tf_ts')
    )
    op.create_index('idx_price_sym_tf_ts', 'price_ohlcv', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_table('risk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('current_drawdown', sa.Float(), nullable=False),
    sa.Column('trading_paused', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_state_date'), 'risk_state', ['date'], unique=False)
    op.create_table('sr_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('price_high', sa.Float(), nullable=False),
    sa.Column('price_low', sa.Float(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('last_touched', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sr_sym_tf', 'sr_zones', ['symbol', 'timeframe'], unique=False)
    op.create_table('swing_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_swing_sym_tf', 'swing_points', ['symbol', 'timeframe'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicator_sym_tf_ts', 'technical_indicators', ['symbol', 'timeframe', 'timestamp', 'indicator_name'], unique=False)
    op.create_table('telegram_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('treasury_yields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenor', sa.String(length=10), nullable=False),
    sa.Column('yield_percent', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_treasury_tenor_date', 'treasury_yields', ['tenor', 'date'], unique=False)
    op.create_table('vix_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('asset_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_zone', sa.Text(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('reevaluation_trigger', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['fundamental_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_sym_date', 'asset_analysis', ['symbol', 'generated_at'], unique=False)
    op.create_index(op.f('ix_asset_analysis_symbol'), 'asset_analysis', ['symbol'], unique=False)
    op.create_table('trade_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_analysis_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_analysis_id'], ['asset_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trigger_status', 'trade_triggers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trigger_status', table_name='trade_triggers')
    op.drop_table('trade_triggers')
    op.drop_index(op.f('ix_asset_analysis_symbol'), table_name='asset_analysis')
    op.drop_index('idx_analysis_sym_date', table_name='asset_analysis')
    op.drop_table('asset_analysis')
    op.drop_table('vix_data')
    op.drop_index('idx_treasury_tenor_date', table_name='treasury_yields')
    op.drop_table('treasury_yields')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('telegram_conversations')
    op.drop_index('idx_indicator_sym_tf_ts', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_table('system_config')
    op.drop_index('idx_swing_sym_tf', table_name='swing_points')
    op.drop_table('swing_points')
    op.drop_index('idx_sr_sym_tf', table_name='sr_zones')
    op.drop_table('sr_zones')
    op.drop_index(op.f('ix_risk_state_date'), table_name='risk_state')
    op.drop_table('risk_state')
    op.drop_index('idx_price_sym_tf_ts', table_name='price_ohlcv')
    op.drop_table('price_ohlcv')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index('idx_position_status', table_name='positions')
    op.drop_table('positions')
    op.drop_table('orders_log')
    op.drop_index(op.f('ix_news_items_source'), table_name='news_items')
    op.drop_index('idx_news_url', table_name='news_items')
    op.drop_index('idx_news_source_fetched', table_name='news_items')
    op.drop_table('news_items')
    op.drop_table('news_digest')
    op.drop_index('idx_liq_sym_tf', table_name='liquidity_zones')
    op.drop_table('liquidity_zones')
    op.drop_table('interest_rates')
    op.drop_index('idx_fvg_sym_tf', table_name='fvg_zones')
    op.drop_table('fvg_zones')
    op.drop_table('fundamental_briefs')
    op.drop_table('fedwatch_probabilities')
    op.drop_index(op.f('ix_economic_calendar_event_time'), table_name='economic_calendar')
    op.drop_index(op.f('ix_economic_calendar_currency'), table_name='economic_calendar')
    op.drop_table('economic_calendar')
    op.drop_table('dxy_data')
    op.drop_index(op.f('ix_cot_report_market_code'), table_name='cot_report')
    op.drop_index('idx_cot_market_date', table_name='cot_report')
    op.drop_table('cot_report')
    op.drop_index(op.f('ix_activity_log_timestamp'), table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
