"""add_trade_outcome_and_paper_trading

Revision ID: b0fde765c72f
Revises: 7da1dc0bfedc
Create Date: 2026-08-08 13:15:41.927656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fde765c72f'
down_revision: Union[str, Sequence[str], None] = '7da1dc0bfedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
