"""Add TokenUsageLog

Revision ID: b7045c4e0a72
Revises: 22f055e65e0b
Create Date: 2026-08-07 08:12:58.678121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7045c4e0a72'
down_revision: Union[str, Sequence[str], None] = '22f055e65e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_log_timestamp'), 'token_usage_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_log_timestamp'), table_name='token_usage_log')
    op.drop_table('token_usage_log')
    # ### end Alembic commands ###
