"""Add source_strategy_id

Revision ID: c71ec30c5875
Revises: 15209555d3e9
Create Date: 2026-08-20 11:45:59.212843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71ec30c5875'
down_revision: Union[str, Sequence[str], None] = '15209555d3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_analysis', sa.Column('source_strategy_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_asset_analysis_source_strategy_id'), 'asset_analysis', ['source_strategy_id'], unique=False)
    op.create_index('uq_position_analysis_open', 'positions', ['analysis_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_position_analysis_open', table_name='positions', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_asset_analysis_source_strategy_id'), table_name='asset_analysis')
    op.drop_column('asset_analysis', 'source_strategy_id')
    # ### end Alembic commands ###
