"""add_missing_constraints_and_indexes

Revision ID: c7ea30d48aee
Revises: 48828461351b
Create Date: 2026-08-22 01:21:17.948870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ea30d48aee'
down_revision: Union[str, Sequence[str], None] = '48828461351b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_calendar_event', 'economic_calendar', ['currency', 'event_name', 'event_time'])
    op.create_index('uq_position_symbol_open', 'positions', ['symbol'], unique=True, postgresql_where=sa.text("status = 'open' AND pair_group_id IS NULL"), sqlite_where=sa.text("status = 'open' AND pair_group_id IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_position_symbol_open', table_name='positions', postgresql_where=sa.text("status = 'open'"), sqlite_where=sa.text("status = 'open'"))
    op.drop_constraint('uq_calendar_event', 'economic_calendar', type_='unique')
    # ### end Alembic commands ###
