"""sync_schema_indexes_types_and_constraints

Revision ID: c83c5e451412
Revises: u2p3j4c5d6e7
Create Date: 2026-10-05 06:40:12.945165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83c5e451412'
down_revision: Union[str, Sequence[str], None] = 'u2p3j4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing_tables = insp.get_table_names()

    if 'economic_report_decompositions' not in existing_tables:
        op.create_table(
            'economic_report_decompositions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('report_type', sa.String(length=30), nullable=False),
            sa.Column('country', sa.String(length=10), nullable=False),
            sa.Column('currency', sa.String(length=10), nullable=False),
            sa.Column('period', sa.String(length=20), nullable=False),
            sa.Column('release_date', sa.DateTime(timezone=True), nullable=False),
            sa.Column('component_name', sa.String(length=120), nullable=False),
            sa.Column('category', sa.String(length=50), nullable=False),
            sa.Column('weight_pct', sa.Float(), nullable=True),
            sa.Column('value_actual', sa.Float(), nullable=False),
            sa.Column('value_forecast', sa.Float(), nullable=True),
            sa.Column('value_previous', sa.Float(), nullable=True),
            sa.Column('mom_change', sa.Float(), nullable=True),
            sa.Column('yoy_change', sa.Float(), nullable=True),
            sa.Column('contribution_bps', sa.Float(), nullable=True),
            sa.Column('is_noise', sa.Boolean(), nullable=False),
            sa.Column('metadata_json', sa.Text(), nullable=True),
            sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('report_type', 'country', 'period', 'component_name', name='uq_report_decomp')
        )

    if 'central_bank_documents' not in existing_tables:
        op.create_table(
            'central_bank_documents',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('bank', sa.String(length=20), nullable=False),
            sa.Column('doc_type', sa.String(length=30), nullable=False),
            sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
            sa.Column('title', sa.String(length=300), nullable=False),
            sa.Column('source_url', sa.String(length=1000), nullable=False),
            sa.Column('full_text', sa.Text(), nullable=False),
            sa.Column('paragraphs_json', sa.Text(), nullable=False),
            sa.Column('hawkish_dovish_score', sa.Float(), nullable=True),
            sa.Column('key_phrases_json', sa.Text(), nullable=True),
            sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('bank', 'doc_type', 'meeting_date', name='uq_cb_doc_record')
        )

    if 'macro_liquidity_credit_metrics' not in existing_tables:
        op.create_table(
            'macro_liquidity_credit_metrics',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('metric_type', sa.String(length=50), nullable=False),
            sa.Column('country', sa.String(length=10), nullable=False),
            sa.Column('record_date', sa.DateTime(timezone=True), nullable=False),
            sa.Column('value', sa.Float(), nullable=False),
            sa.Column('previous_value', sa.Float(), nullable=True),
            sa.Column('change_value', sa.Float(), nullable=True),
            sa.Column('unit', sa.String(length=20), nullable=False),
            sa.Column('regime', sa.String(length=30), nullable=True),
            sa.Column('metadata_json', sa.Text(), nullable=True),
            sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('metric_type', 'country', 'record_date', name='uq_macro_liq_metric')
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pattern_screening_cache_screened_at'), 'pattern_screening_cache', ['screened_at'], unique=False)
    op.create_index(op.f('ix_pattern_screening_cache_symbol'), 'pattern_screening_cache', ['symbol'], unique=False)
    op.alter_column('telegram_conversations', 'telegram_user_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_telegram_topic_session_id'), 'telegram_topic_bindings', type_='unique')
    op.drop_index(op.f('ix_telegram_topic_bindings_session_id'), table_name='telegram_topic_bindings')
    op.create_index(op.f('ix_telegram_topic_bindings_session_id'), 'telegram_topic_bindings', ['session_id'], unique=True)
    op.alter_column('trade_triggers', 'asset_analysis_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_triggers', 'asset_analysis_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_telegram_topic_bindings_session_id'), table_name='telegram_topic_bindings')
    op.create_index(op.f('ix_telegram_topic_bindings_session_id'), 'telegram_topic_bindings', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('uq_telegram_topic_session_id'), 'telegram_topic_bindings', ['session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('telegram_conversations', 'telegram_user_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_pattern_screening_cache_symbol'), table_name='pattern_screening_cache')
    op.drop_index(op.f('ix_pattern_screening_cache_screened_at'), table_name='pattern_screening_cache')
    op.drop_table('macro_liquidity_credit_metrics')
    op.drop_table('central_bank_documents')
    op.drop_table('economic_report_decompositions')
    # ### end Alembic commands ###
