"""sync_trade_plan_legs_and_backtest_trade

Revision ID: ce03bbdda5af
Revises: j1a2b3c4d5e6
Create Date: 2026-09-06 03:12:18.163745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce03bbdda5af'
down_revision: Union[str, Sequence[str], None] = 'j1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    try:
        insp = sa.inspect(conn)
        existing_tables = set(insp.get_table_names())
    except Exception:
        existing_tables = set()

    if 'trading_events' not in existing_tables:
        op.create_table(
            'trading_events',
            sa.Column('id', sa.String(length=36), nullable=False, primary_key=True),
            sa.Column('seq', sa.Integer(), nullable=True),
            sa.Column('event_type', sa.String(length=128), nullable=False),
            sa.Column('correlation_id', sa.String(length=64), nullable=False),
            sa.Column('causation_id', sa.String(length=64), nullable=True),
            sa.Column('payload', sa.JSON(), nullable=False),
            sa.Column('actor', sa.String(length=50), nullable=False, server_default='system'),
            sa.Column('ts_created', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        )
        op.create_index('ix_trading_events_seq', 'trading_events', ['seq'], unique=False)
        op.create_index('ix_trading_events_event_type', 'trading_events', ['event_type'], unique=False)
        op.create_index('ix_trading_events_correlation_id', 'trading_events', ['correlation_id'], unique=False)
        op.create_index('ix_trading_events_ts_created', 'trading_events', ['ts_created'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_trade', sa.Column('executed_lots', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_bond_yield_country_date'), table_name='bond_yield_data')
    op.drop_constraint(op.f('uq_bond_yield'), 'bond_yield_data', type_='unique')
    op.create_index('idx_bond_yield_ct_date', 'bond_yield_data', ['country_tenor', 'date'], unique=False)
    op.create_unique_constraint('uq_bond_yield_country_date', 'bond_yield_data', ['country_tenor', 'date'])
    op.create_index(op.f('ix_mt5_signals_asset_analysis_id'), 'mt5_signals', ['asset_analysis_id'], unique=False)
    op.drop_constraint(op.f('order_events_order_id_fkey'), 'order_events', type_='foreignkey')
    op.create_foreign_key(None, 'order_events', 'orders', ['order_id'], ['id'])
    op.create_index(op.f('ix_paper_trade_records_analysis_id'), 'paper_trade_records', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_positions_analysis_id'), 'positions', ['analysis_id'], unique=False)
    op.create_index('idx_tg_user_timestamp', 'telegram_conversations', ['telegram_user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telegram_conversations_telegram_user_id'), 'telegram_conversations', ['telegram_user_id'], unique=False)
    op.alter_column('token_usage_log', 'thinking_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_trade_outcomes_analysis_id'), 'trade_outcomes', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_position_id'), 'trade_outcomes', ['position_id'], unique=False)
    existing_trade_plan_leg_cols = set()
    if 'trade_plan_legs' in existing_tables:
        try:
            existing_trade_plan_leg_cols = {c['name'] for c in insp.get_columns('trade_plan_legs')}
        except Exception:
            existing_trade_plan_leg_cols = set()

    for col_name, col_def in [
        ('target_entry', sa.Column('target_entry', sa.Float(), nullable=False, server_default='0.0')),
        ('actual_entry', sa.Column('actual_entry', sa.Float(), nullable=True)),
        ('ticket_id', sa.Column('ticket_id', sa.Integer(), nullable=True)),
        ('position_id', sa.Column('position_id', sa.Integer(), nullable=True)),
        ('filled_at', sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True)),
        ('pnl_usd', sa.Column('pnl_usd', sa.Float(), nullable=True)),
    ]:
        if col_name not in existing_trade_plan_leg_cols:
            op.add_column('trade_plan_legs', col_def)

    if 'trade_plan_legs' in existing_tables:
        try:
            op.alter_column('trade_plan_legs', 'status',
                       existing_type=sa.VARCHAR(length=30),
                       type_=sa.String(length=20),
                       existing_nullable=False,
                       existing_server_default=sa.text("'PENDING'::character varying"))
        except Exception:
            pass

    for idx_name in ['ix_trade_plan_legs_mt5_ticket', 'ix_trade_plan_legs_status']:
        try:
            op.drop_index(op.f(idx_name), table_name='trade_plan_legs')
        except Exception:
            pass

    for fk_name in [op.f('trade_plan_legs_plan_id_fkey')]:
        try:
            op.drop_constraint(fk_name, 'trade_plan_legs', type_='foreignkey')
        except Exception:
            pass

    try:
        op.create_foreign_key(None, 'trade_plan_legs', 'trade_plans', ['plan_id'], ['id'])
    except Exception:
        pass

    try:
        op.create_foreign_key(None, 'trade_plan_legs', 'positions', ['position_id'], ['id'])
    except Exception:
        pass

    for col_name in ['created_at', 'realized_pnl', 'exit_reason', 'entry_price', 'mt5_ticket', 'updated_at', 'opened_at']:
        if col_name in existing_trade_plan_leg_cols:
            op.drop_column('trade_plan_legs', col_name)
    op.create_index(op.f('ix_trade_triggers_asset_analysis_id'), 'trade_triggers', ['asset_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_triggers_asset_analysis_id'), table_name='trade_triggers')
    op.add_column('trade_plan_legs', sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('trade_plan_legs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('trade_plan_legs', sa.Column('mt5_ticket', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trade_plan_legs', sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trade_plan_legs', sa.Column('exit_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trade_plan_legs', sa.Column('realized_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trade_plan_legs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trade_plan_legs', type_='foreignkey')
    op.drop_constraint(None, 'trade_plan_legs', type_='foreignkey')
    op.create_foreign_key(op.f('trade_plan_legs_plan_id_fkey'), 'trade_plan_legs', 'trade_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_trade_plan_legs_status'), 'trade_plan_legs', ['status'], unique=False)
    op.create_index(op.f('ix_trade_plan_legs_mt5_ticket'), 'trade_plan_legs', ['mt5_ticket'], unique=False)
    op.alter_column('trade_plan_legs', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_column('trade_plan_legs', 'pnl_usd')
    op.drop_column('trade_plan_legs', 'filled_at')
    op.drop_column('trade_plan_legs', 'position_id')
    op.drop_column('trade_plan_legs', 'ticket_id')
    op.drop_column('trade_plan_legs', 'actual_entry')
    op.drop_column('trade_plan_legs', 'target_entry')
    op.drop_index(op.f('ix_trade_outcomes_position_id'), table_name='trade_outcomes')
    op.drop_index(op.f('ix_trade_outcomes_analysis_id'), table_name='trade_outcomes')
    op.alter_column('token_usage_log', 'thinking_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_telegram_conversations_telegram_user_id'), table_name='telegram_conversations')
    op.drop_index('idx_tg_user_timestamp', table_name='telegram_conversations')
    op.drop_index(op.f('ix_positions_analysis_id'), table_name='positions')
    op.drop_index(op.f('ix_paper_trade_records_analysis_id'), table_name='paper_trade_records')
    op.drop_constraint(None, 'order_events', type_='foreignkey')
    op.create_foreign_key(op.f('order_events_order_id_fkey'), 'order_events', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_mt5_signals_asset_analysis_id'), table_name='mt5_signals')
    op.drop_constraint('uq_bond_yield_country_date', 'bond_yield_data', type_='unique')
    op.drop_index('idx_bond_yield_ct_date', table_name='bond_yield_data')
    op.create_unique_constraint(op.f('uq_bond_yield'), 'bond_yield_data', ['country_tenor', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('idx_bond_yield_country_date'), table_name='bond_yield_data')
    op.drop_column('backtest_trade', 'executed_lots')

    conn = op.get_bind()
    try:
        insp = sa.inspect(conn)
        existing_tables = set(insp.get_table_names())
    except Exception:
        existing_tables = set()
    if 'trading_events' in existing_tables:
        op.drop_table('trading_events')
    # ### end Alembic commands ###
